### ISSUE TITLE
Freb logs are not shown of FREB directory is mounted to a host

### ISSUE THREAD

**Issue by artisticcheese** [Microsoft/IIS.Administration#111]
I mount my FREB folder to a host withing container and when I do that UI in IISAdmin does not show TraceLogs. No error is shown. Settings and rules works fine and log is being generated on host but IIAdmin seems to be missing permissions or something else. Not sure.

**Comment by jimmyca15** [comment]
Are you changing the physical location of the FREB files in the IIS configuration? If you are using a folder outside of inetpub it will not show up in the UI unless you specify read access to that folder in the appsettings.json file.

**Comment by artisticcheese** [comment]
My freb files are still in inetpub but they are mapped to a host inside container via `volume`

**Comment by jimmyca15** [comment]
If use the files UI and go to the inetpub/logs/logfiles/freb folder do you get access denied?

The IIS Administration API resolves symbolic links/mounting points before checking to see if a file path is allowed. This behavior can be turned off with the _skip_resolving_symbolic_links_ setting in the [files](https://docs.microsoft.com/en-us/iis-administration/configuration/appsettings.json#files) section of the appsettings.json

**Comment by artisticcheese** [comment]
Gettings `access denied` when using `Files` menu. So I need to construct my files part in appsettings.json as below? I'm not sure where to put that property in JSON file.
```
"files": {
"skip_resolving_symbolic_links":  "true",
    "locations": [
      {
        "alias": "inetpub",
        "path": "%systemdrive%\\inetpub",
        "claims": [
          "read",
          "write"
        ]
      }
    ]
  }
```

**Comment by jimmyca15** [comment]
Yes, that is the correct location for the _skip_resolving_symbolic_links_ setting. When this flag is set to true, the API will not resolve the mount point and will check the original path (c:\inetpub\wwwroot\....) when checking if the path is allowed.

**Comment by artisticcheese** [comment]
yes, that fixed it.
