### ISSUE TITLE
IIS Website is stopped after POST

### ISSUE THREAD

**Issue by Caloyski** [Microsoft/IIS.Administration#116]
Is there a way to start a website as soon as it's created?

**Comment by jimmyca15** [comment]
As long as the web site is valid, the binding does not conflict with another binding, and server_auto_start is true the web site should start automatically.

**Comment by Caloyski** [comment]
Yes, you're right. I found that the problem was that there was another site that had an empty hostname and I didn't set the hostname on POST for the new site. Thanks!
