### ISSUE TITLE
Bindings: hostname cannot be set or modified

### ISSUE THREAD

**Issue by Caloyski** [Microsoft/IIS.Administration#117]
I'm trying to create a new site with its hostname. The API call is successfull but there's no hostname property when I GET it.
I'm trying to PATCH it too, but again, with no results.

**Comment by jimmyca15** [comment]
Can you provide what POST and PATCH request you are sending to the API.

My guess would be that when you are sending the request to the API you are providing the _binding_information_ property which takes precedence over the _hostname_ property. The _binding_information_ property provides a way to set binding properties in the raw format used by IIS -> ip_address:port:hostname.

For example if I send

```
"bindings": [
  {
    "ip_address": "*",
    "port": "80",
    "hostname": "contoso",
    "binding_information": "*:80:"
  }
]
```

_binding_information_ will set _hostname_ to "".

**Comment by Caloyski** [comment]
Yes, that was it! Thanks!

**Comment by jimmyca15** [comment]
You're welcome, feel free to raise another issue if you have more concerns.
