### ISSUE TITLE
Installation Problems

### ISSUE THREAD

**Issue by kim182** [Microsoft/IIS.Administration#128]
As following issue: https://github.com/Microsoft/IIS.Administration/issues/59
i could not install version 2.1. But in this case, i have a Windows Server 2012 R2 Standard. 
No internet access, so dotnet core 1.12 and vcc 2015 upd3 redist previously installed. 
![imagen](https://user-images.githubusercontent.com/5789657/29377964-cba00c6a-8293-11e7-8412-e45c7aa30a98.png)

Log Entry:
![imagen](https://user-images.githubusercontent.com/5789657/29376837-43a05750-8290-11e7-8057-792e0169bf21.png)

I tried with 2 different machines. 
Then, on a Windows 10 environment, this installed succesfully. 

Thanks in advance

Martin

**Comment by jimmyca15** [comment]
I see that you said that you have .NET Core 1.1.2, do you also have 1.0.* installed or did you install only the 1.1.* version of .NET Core. The IIS Administration API requires the 1.0.* release of .NET Core to run.

**Comment by kim182** [comment]
That was it! Thank you

**Comment by jimmyca15** [comment]
Glad to hear that it worked. Thanks for filing the issue. We will enhance the installer for this scenario so that the logs will be more helpful.
