### ISSUE TITLE
Always get forbidden on the physical_path when creating a website

### ISSUE THREAD

**Issue by ricmrodrigues** [Microsoft/IIS.Administration#130]
Not sure what's going on, the Network Credential supplied is an admin on the machine, same user I've used to create the physical path full path, but I always get:

`{"title":"Forbidden","name":"physical_path","detail":"c:\\teste\\teste2","status":403}`

StatusCode: Forbidden

Which from what I understand is coming from `FileProvider.IsAccessAllowed`

**Comment by jimmyca15** [comment]
In order to be able to create a web site, the physical path must be visible to the API. Access to the file system is configured through the application's [appsettings.json](https://docs.microsoft.com/en-us/iis-administration/configuration/appsettings.json) file.

For example to create the site where you mentioned you would need a configuration such as

```
  "files": {
    "locations": [
      {
        "alias": "site_testing",
        "path": "c:\\teste",
        "claims": [
          "read"
        ]
      }
    ]
  }
```

**Comment by ricmrodrigues** [comment]
Excellent, that worked! This is a dependency for another project of mine, how do I ensure the permissions are correctly set when this is being deployed?

**Comment by jimmyca15** [comment]
How are you installing the application and in what environment?

**Comment by ricmrodrigues** [comment]
Using the manage.iis.net download the app's installer and installing it on windows 10/server 2012 R2.
If I could silently install this, better.

**Comment by jimmyca15** [comment]
Running the installer with the following flags should execute a silent install.
`
IISAdministrationSetup.exe /install /q /norestart
`

Right now there is no way to specify settings when installing, you will have to have a post install method to update the configuration. Possibly by copying a pre-configured appsettings.json file from a share or by writting in the missing sections.

**Comment by jimmyca15** [comment]
Looks like this issue was solved. I'll go ahead and close it.
