### ISSUE TITLE
How do I keep track where to put configuration values to for different versions of IIS Admin

### ISSUE THREAD

**Issue by artisticcheese** [Microsoft/IIS.Administration#131]
Hello,

My current dockerfile installs IIS administration and the copies precreated shared key. Problem arises when new version of IISAdmin is released location of `appsettings.json` file changes as well. What could be permament solution to this?
```
ADD "http://go.microsoft.com/fwlink/?LinkId=829373" ".\iisadmin.exe"
COPY ["appsettings.json","C:\\Program Files\\IIS Administration\\2.0.0\\Microsoft.IIS.Administration\\config\\appsettings.json"]
RUN start-process -Filepath .\iisadmin.exe -ArgumentList  @('/install', '/q', '/norestart') -Wait 
```

**Comment by jimmyca15** [comment]
As it stands today, as long as the installer is being downloaded and then installed we would have to check which version we installed. The other option is only install a known version to ensure that the settings path is accurate.

I am thinking of solutions to this problem and one solution I am considering is the ability to place the appsettings.json in a version agnostic location such as _C:\Program Files\IIS Administration\config_.

**Comment by artisticcheese** [comment]
Yes, please do version agnostic setup may be or how do I download specific version of EXE installer?

**Comment by jimmyca15** [comment]
We only have a download link available for the latest release and that's the same link that your container is already pointing too. I would rather work on the version agnostic setup approach.

**Comment by artisticcheese** [comment]
OK. Either one will work for automated container images.
