### ISSUE TITLE
Possible code improvements in ModulesId.cs and CorsExtensions.cs

### ISSUE THREAD

**Issue by Ky7m** [Microsoft/IIS.Administration#132]
There are two places in the code that are not clear and might lead to potential issues:

1. [Microsoft.IIS.Administration.WebServer.Modules/ModulesId.cs#L63](https://github.com/Microsoft/IIS.Administration/blob/dev/src/Microsoft.IIS.Administration.WebServer.Modules/ModulesId.cs#L63)
```csharp
this.IsLocal = IsLocal;
```
Variable is assigned to itself, probably it should use parameter `isLocal` from the constructor.

2. [Microsoft.IIS.Administration/Cors/CorsExtensions.cs#L25](https://github.com/Microsoft/IIS.Administration/blob/master/src/Microsoft.IIS.Administration/Cors/CorsExtensions.cs#L25)
```csharp
// Allow CORs for rootPath only
if (!string.IsNullOrEmpty(rootPath) || rootPath != "/")
```
Probably `&&` operator should be used instead of `||`, if comment is correct.

**Does it make sense?**

**Comment by jimmyca15** [comment]
Yes these are both valid. Thanks for finding them and pointing them out.

**Comment by Ky7m** [comment]
I know that it is 5-10 minutes for you to fix them, but let me know if I can assist you there and create a PR.
