### ISSUE TITLE
Packager project: issues with custom post build events on non-Windows platform

### ISSUE THREAD

**Issue by Ky7m** [Microsoft/IIS.Administration#133]
Current [post build commands](https://github.com/Microsoft/IIS.Administration/blob/dev/src/Packager/Packager/Packager.csproj) work correctly on Windows platform only. On macOS and Linux platforms, solution build throws errors.

**Comment by jimmyca15** [comment]
The packager project was changed to use msbuild to support code signing functionality for the project. To fix the issue we will need to only execute msbuild if the signing is requested. If $(SignType) is defined then signing is enabled for the build.
