### ISSUE TITLE
Project Dead?

### ISSUE THREAD

**Issue by sundarchi1** [Microsoft/IIS.Administration#138]
With the release of "Project Honolulu", is this IIS.Administration project being discontinued?

Hasn't been much substantial activity lately here. Honolulu shares a very similar UI, so I'm curious if all this is just going to be put in there soon?

https://blogs.technet.microsoft.com/windowsserver/2017/09/22/project-honolulu-technical-preview-is-now-available-for-download/

**Comment by jimmyca15** [comment]
@sundarchi1,

No the IIS Administration project will not be discontinued. There are a few things that the IIS Administration API gives us that make it valuable in itself.
1. REST API accessible by any client that can communicate with HTTP
2. Created specifically for IIS with full coverage of the Web Server role in mind

There is no doubt that Project Honolulu is a valuable integration point for Windows Roles in the future and an IIS Extension may arise.

There were recently some other projects that took us away from this for a bit, but we will be finishing up our next feature soon. The last bit of work that has been done is on a Health Monitoring API. When this API is completed we will also be updating https://manage.iis.net to utilize it and display statistics regarding the health/performance of the webserver. The work is currently on the [jimmyca15/monitoring](https://github.com/Microsoft/IIS.Administration/tree/jimmyca15/monitoring) branch and will be merged in when completed if you'd like to take a look.
