### ISSUE TITLE
Not able to debug in vs2017 15.3.5

### ISSUE THREAD

**Issue by babula38** [Microsoft/IIS.Administration#139]
Hi, I am not able to debug the application in the above mentioned visual studio instance do I have to change some thing to make it debug.

" The project doesn't know how to run the profile IIS Express"

**Comment by jimmyca15** [comment]
When you load the solution try building restoring NuGet packages to ensure the SDK is hooked up correctly into visual studio. Once this is done VS should load the _Microsoft.IIS.Administration_ launch profile from the launchsettings.json file in the main project.

Also before developing make sure to run the Configure-DevEnvironment.ps1 script in the scripts dir. 

It looks like this script may need to be updated to copy appsettings.default.json to a file named appsettings.json as well as copying modules.default.json to just be modules.json

**Comment by jimmyca15** [comment]
Closing this since there has been no response.

**Comment by babula38** [comment]
Hi sorry for the late response. I was busy on implementing you steps to make the application work but still it is not working I tried for both the branches dev and master.
below are the steps I use to compile and run.

1. download the source code from the repo any branch dev/master
2. loaded the solution as administrator in vs 2017(15.3.5)
3. Execute the script "Configure-DevEnvironment" under scripts folder.
4. two files "appsettings,modules" got created under "Microsoft.IIS.Administration\config" folder.
5. build the solution successfully.
6. bydefult "iis express" profile is  sleeted, now run the application.

Error:-The project doesn't know how to run the profile IIS Express.

![git](https://user-images.githubusercontent.com/4153708/31368847-ccae1c0c-ad9d-11e7-9535-cef24301240c.PNG)


please let me know if I am missing something. if you want I can share my system with you anytime you want.
