### ISSUE TITLE
Installation Issues

### ISSUE THREAD

**Issue by hahndorf** [Microsoft/IIS.Administration#15]
So I'm trying to check this out, I'm using a fresh 2012 R2 machine.

I first installed the prerequisites: 

    dism.exe /online /enable-feature /featurename:IIS-WindowsAuthentication /all 
    dism.exe /online /enable-feature /featurename:IIS-HostableWebCore /all
    .\DotNetCore.1.0.0-WindowsHosting.exe /install /quiet

and dotnet core seems to work.

I downloaded a zip of the repository and extracted it into C:\inetpub

running:

      C:\inetpub\IIS.Administration\scripts\publish\publish.ps1

complains about a missing parameter `-outputPath` as the script is not documented I don't know what that means, so I provide just an empty folder.

The scripts breaks at line 173: `"Could not build plugins for publishing"`, the dotnet publish command fails in `Microsoft.DotNet.Tools.Publish.PublishCommand.TryPrepareForPublish()`: `System.InvalidOperationException: Collection was modified; enumeration operation may not execute.`

Also the output directory `IIS.Administration\src\Microsoft.IIS.Administration\plugins` does not exist, but maybe dotnet.exe creates that if it would work.

At this point I stopped.

Also the publish.ps1 script has a URL:

    http://gitlab/jimmyca/Microsoft.IIS.Administration.Host/repository/archive.zip?ref=master

that's an internal resource that surely will not work for me.

**Comment by jimmyca15** [comment]
@hahndorf 
I'm sorry for the confusion. Currently because of the internal resource that you mentioned, publishing is not fully functional yet. I am currently working on the distribution mechanism that we will be using to replace that internal link. Until I do that, publishing and installing from the published output will not work.

**Comment by jimmyca15** [comment]
I'm reopening this because the availability of the internal resource was not the only issue. It looks like another issue was encountered because the project was not restored.

**Comment by jimmyca15** [comment]
I tested out the scenario you provided with the changes made in #20. The publish was successful. At this point there should be no issues running the publish script from the zip copy of the repository. Once the publish succeeds installation can be done directly from the setup script in the published output.
