### ISSUE TITLE
Wrong date in self signed certificates created during install

### ISSUE THREAD

**Issue by radykal-com** [Microsoft/IIS.Administration#151]
Hello,

During the install of this tool, a self-signed certificate is created and added as trusted root. The problem is, if the server running the install is in a different timezone than UTC, the datetime generated for the certificate is using the local time (with timezone applied) but the timezone in the certificates are supposed to be always UTC.

I'm running it in servers under CEST timezone which right now is UTC+2, so the generated certificates are not valid until 2hours-10minutes away from certificate creation.

**Comment by jimmyca15** [comment]
I just confirmed the issue, thanks for making the PR.

**Comment by radykal-com** [comment]
You are welcome!
