### ISSUE TITLE
Generate-AccessTokens does not work if Internet Explorer is not present or initial configuration wizard has not been completed

### ISSUE THREAD

**Issue by radykal-com** [Microsoft/IIS.Administration#155]
Hello,

I'm trying to use this tool to provision webservices servers in the cloud in an unattended way.
To do so, I'm trying to generate a first access token by provisioning a copy of the utils.ps1 script and calling the Generate-AccessTokens command.
The problem is that the command uses Invoke-WebRequest to make the HTTP requests and the default usage of the Invoke-WebRequest cmdlet requires Internet Explorer to be installed and with the initial wizard already ran or it shows the error 

> The response content cannot be parsed because the Internet Explorer engine is not available, or Internet Explorer's first-launch configuration is not complete. Specify the UseBasicParsing parameter and try  again.

Would be nice to be able to run the script in servers without Internet Explorer and without having to initialize internet explorer for first time.

As documented here https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/invoke-webrequest?view=powershell-5.1#optional-parameters passing the -UseBasicParsing works fine, other way would be to use the .NET WebRequest objects without the Invoke-WebRequest cmdlet

I can provide the PR with the new parameter in the 2 Invoke-WebRequest calls if needed

**Comment by jimmyca15** [comment]
The UseBasicParsing option is the better approach. If you want to submit a PR for the change that would be great, otherwise I can get to it. That file also has some spacing inconsistencies that need to be fixed.

**Comment by radykal-com** [comment]
The PR also replaces all tabs with 4 spaces and removes some trailing tabs that were present in a line
