### ISSUE TITLE
How should I set up username and password and domain?

### ISSUE THREAD

**Issue by cakey90** [Microsoft/IIS.Administration#159]
I want to use api client

``` C#
var httpClientHandler = new HttpClientHandler() {
    Credentials = new NetworkCredential(userName, password, domain)
};
var apiClient = new HttpClient(httpClientHandler);

// Set access token for every request
apiClient.DefaultRequestHeaders.Add("Access-Token", "Bearer {token}");
```

How should I set up username and password and domain?
I'm a new developer-。-

**Comment by jimmyca15** [comment]
The username and password are your Windows username and password. The domain is the domain that the user is a part of. If your machine is not domain joined then the [NetworkCredential](https://msdn.microsoft.com/en-us/library/system.net.networkcredential(v=vs.110).aspx) constructor without a domain should be used.

**Comment by cakey90** [comment]
Thanks! I ran it successfully.

**Comment by jimmyca15** [comment]
Great news. For more documentation on the IIS Administration API you can check out https://docs.microsoft.com/en-us/iis-administration/
