### ISSUE TITLE
application is repeated in content types

### ISSUE THREAD

**Issue by jimmyca15** [microsoft/IIS.Administration#169]
API content types have the term application repeated. 

application/vnd.Microsoft.WebServer.AppPools.2.2.0.application/hal+json; charset=utf-8

should be

application/vnd.Microsoft.WebServer.AppPools.2.2.0.hal+json; charset=utf-8

**Comment by babula38** [comment]
@jimmyca15 I tried to fix the issue, as I am new to GitHub I do not know how the pull and fork works. so rolled back the changes. But if you want you can have a check on this change logs and let me know your feedback. 
Thanks.
