### ISSUE TITLE
Package restore failed

### ISSUE THREAD

**Issue by MaherJendoubi** [Microsoft/IIS.Administration#17]
![image](https://cloud.githubusercontent.com/assets/1798510/18897935/965626d8-852e-11e6-905a-58a132ece90f.png)

**Comment by MaherJendoubi** [comment]
error: Unable to resolve 'xunit (>= 2.2.0-beta3-build3401)' for '.NETCoreApp,Version=v1.0'.
error: Unable to resolve 'dotnet-test-xunit (>= 2.2.0-preview3-build1047)' for '.NETCoreApp,Version=v1.0'.

**Comment by jimmyca15** [comment]
This problem doesn't exist anymore until we bump the version back to 1.0.1. When we do that we will bump the .NETCoreApp version of the tests project which will fix the issue.
