### ISSUE TITLE
Custom certificate bindings not preserved on upgrade

### ISSUE THREAD

**Issue by jimmyca15** [microsoft/IIS.Administration#170]
A user reported that they replaced the generated IIS Administration certificate with their own certificate for SSL communication, but after upgrading the IIS Administration certificate was being used once again.

The offending piece of code appears to be at https://github.com/Microsoft/IIS.Administration/blob/dev/scripts/setup/migrate.ps1#L131. 

If the migration logic sees that the previous installation is using a non _IIS Administration API Server Certificate_ cert, then it should leave it alone.

**Comment by EatonZ** [comment]
That user being me.😉
Don't forget to also fix the issue where the port 55540 stuck around after the upgrade too.

**Comment by EatonZ** [comment]
@jimmyca15 Any luck fixing these? Are there any updates coming with the Windows RS4 release?

**Comment by jimmyca15** [comment]
Haven't fixed these yet since there hasn't been a new release planned. There aren't any updates coming out in the timeline of the Windows RS4 release. We are currently working on some other IIS features in the meantime and then will come back to the IIS Administration API for some planned enhancements, some listed in the issues with the Enhancement label.

**Comment by bariscaglar** [comment]
> Don't forget to also fix the issue where the port 55540 stuck around after the upgrade too.

@EatonZ Is there a separate issue filed for that? If not please do so.

**Comment by EatonZ** [comment]
@bariscaglar It's here: https://github.com/Microsoft/IIS.Administration/issues/172

**Comment by bariscaglar** [comment]
Thanks!

**Comment by EatonZ** [comment]
@jimmyca15 @bariscaglar Just curious when the next release might be? Haven't seen much activity here.

**Comment by jimmyca15** [comment]
@EatonZ thanks for asking. The team has been busy doing some satellite work for IIS Management, and have not begun work on the features that I mentioned we had planned for the IIS Administration API at this point. Since the two issues that you have filed are upgrade bugs we haven't closed them out yet or released an intermediary fix since there isn't anything to upgrade to. I do not have a set time when we will tackle the enhancements I mentioned previously, but they are planned.
