### ISSUE TITLE
Is there will be webdeploy or FTP API?

### ISSUE THREAD

**Issue by cakey90** [Microsoft/IIS.Administration#171]
Hi guy!
Is there will be webdeploy or FTP API?
I want to use IIS WebDeploy or FTP, after I create a website.

**Comment by jimmyca15** [comment]
There are no plans to create API endpoints for web deploy or FTP, however file manipulation can be done through the [files API](https://docs.microsoft.com/en-us/iis-administration/api/files). This endpoint can be used to retrieve, create, edit, and delete files. This is is the same API set that https://manage.iis.net uses to provide file explorer behavior as shown in this [Files API blog post](https://blogs.iis.net/adminapi/iis-administration-preview-1-0-38-introducing-the-files-api).

**Comment by cakey90** [comment]
OK, i see! Files Api I've been using ~! Thanks!
