### ISSUE TITLE
manage.iis.net on premises?

### ISSUE THREAD

**Issue by dhirschfeld** [Microsoft/IIS.Administration#175]
Can the `manage.iis.net` webapp be installed on premises so that it can be used to manage IIS webservers on containers behind a corporate firewall?

**Comment by jimmyca15** [comment]
We do not package the `manage.iis.net` web app to be deployed locally. However, the project is open source and can be found at https://github.com/microsoft/iis.webmanager. Anyone is free to build it and run it themselves.

In the future when development has completed we may offer a packaged version that we bundle and deliver. At the moment, there is a lot of development still being done for this UI, and having it located centrally at `manage.iis.net` ensures that users can easily obtain and offer feedback on the latest version.

**Comment by jimmyca15** [comment]
If you would like to take the option to build it and run it from source code, please do let me know if you encounter any trouble. It should be as straightforward as downloading the sources, building in visual studio, and then hosting it in an IIS web site.

**Comment by drago-draganov** [comment]
If you run the webapp on-prem, make sure to allow it's origin (IP, domain) in all instances of the API it's supposed to manage. Refer to CORS section of the appsettings.json ([more info](https://docs.microsoft.com/en-us/iis-administration/configuration/appsettings.json))

```json
"cors": {
    "rules": [
      {
        "origin": "{origin_of_the_webapp}",
        "allow": true
      }
    ]
  }
```

**Comment by dhirschfeld** [comment]
Thanks for the tip (and the link!)

**Comment by jimmyca15** [comment]
@dhirschfeld 
No worries. I will go ahead and close the issue since it appears the question has been answered.
