### ISSUE TITLE
Locally compiled version is looking for resources not included in the folders

### ISSUE THREAD

**Issue by Ngobskie** [Microsoft/IIS.Administration#181]
I was able to compile the cloned files and added it to my local IIS server. When I tried to access it, it's looking for resources not included in the compiled folders. (i.e. main.v2.2.1.js). The compiled version doesn't have version number in it while the application is looking for the resource with the version number in the filename. Hope you can help me with this.

thank you very much

**Comment by jimmyca15** [comment]
Were you meaning to file this issue into the [IIS.WebManager](https://github.com/Microsoft/IIS.WebManager) repository?

**Comment by Ngobskie** [comment]
Thanks for the reply Jimmy. Yes, I cloned the files from iis.webmanager and compiled it locally

**Comment by Ngobskie** [comment]
Sorry, I think I posted on the wrong project. This is IIS.Administration. Should I close this and repost on the other project?

**Comment by jimmyca15** [comment]
Yes please.

**Comment by Ngobskie** [comment]
Thanks Jimmy
