### ISSUE TITLE
Python or Node

### ISSUE THREAD

**Issue by umardraz** [Microsoft/IIS.Administration#185]
Hello is there anyway to use this API with Python or Nodejs code?

**Comment by babula38** [comment]
Do you means you want to write a Python or Nodejs client and consume apis? if this is the case then sure you can, as IIS.Administration exposes REST Apis . So any language which is capable of handing http request and response  can make call to this Api.

**Comment by umardraz** [comment]
Thanks for your answer.

I had done it
