### ISSUE TITLE
How to remove application

### ISSUE THREAD

**Issue by umardraz** [Microsoft/IIS.Administration#187]
Hello 

How to remove an application from a website.?

**Comment by jimmyca15** [comment]
Send a delete request to the application's *self* link.

**Comment by jimmyca15** [comment]
Copying is supported with the [copy API](https://docs.microsoft.com/en-us/iis-administration/api/files#copyingmoving-files-apifilescopy--apifilesmove).

**Note:** File operations are subject to [file security settings](https://docs.microsoft.com/en-us/iis-administration/configuration/appsettings.json#files).
