### ISSUE TITLE
Missing Save button

### ISSUE THREAD

**Issue by dermeister0** [Microsoft/IIS.Administration#190]
IIS Administration UI looks like phone settings. I have no idea when settings are applied. I don't think it's a good solution for web server administration software.

![2018-08-06_175600](https://user-images.githubusercontent.com/4054844/43713054-7c4c90a8-99a2-11e8-93f5-f236c885da4a.png)

I tried to change app pool recycling interval - it's never saved.

**Comment by jimmyca15** [comment]
@dermeister0 everything is auto saved. Once you change the recycle interval press enter or click away and it should update the value. If its not updating then there is some unknown issue occurring. There are log files for the IIS Administration API at `C:\Program Files\IIS Administration\logs`. There might be a server error occurring that is preventing the value from being updated. It would show up in the logs if there was.

**Comment by dermeister0** [comment]
It works if I press Enter. There is no other way to save the setting, because all controls on the tab are interactive (not text boxes).

There is not visual indicator that field is updated.

Another problem:
I try to change app pool identity. I changed username and pressed Tab - web request is sent to server to patch username only. It does not make sense to change username without password.

![2018-08-07_104943](https://user-images.githubusercontent.com/4054844/43753442-05e0f20e-9a30-11e8-839b-c9dde07e78d0.png)

**Comment by dermeister0** [comment]
Changed value in drop-down list by mistake - there is no way to cancel the change. Everything is applied already.

![2018-08-07_105559](https://user-images.githubusercontent.com/4054844/43753571-af864534-9a30-11e8-85d5-dfab426bcaec.png)

![2018-08-07_105612](https://user-images.githubusercontent.com/4054844/43753575-b1fb6768-9a30-11e8-8fe6-5ffd4dae1e15.png)

For example, press Left, Right, Up or Down when focus is inside drop-down list.

**Comment by dermeister0** [comment]
Enter wrong value to **Time Interval**. A warning is shown, **Periodically** check-box value changed.

![00](https://user-images.githubusercontent.com/4054844/43754042-e55aed2a-9a32-11e8-8f45-facaa2c00286.png)

Return to main page, open application pool again - it displays wrong values. Need to refresh entire page (F5) to reload actual values.

![01](https://user-images.githubusercontent.com/4054844/43754044-e8c7e68e-9a32-11e8-9d6b-290ff8eeac84.png)

**Comment by jimmyca15** [comment]
@dermeister0 it looks like you found a bug with the app pool identity not updating the password. I traced it back to [this line](https://github.com/Microsoft/IIS.WebManager/blob/master/app/utils/diff.ts#L12) where the wrong varialbe is used in a comparison to check what properties to send to the server. I'll look into getting a hotfix released for it.

We can also change the behavior of the perodic recycling switch so that if there is an invalid input it will stay open so that it can be rectified.

Thanks for filing these issues!

**Comment by bariscaglar** [comment]
@jimmyca15 have you had a chance to do this?

**Comment by jimmyca15** [comment]
These problems are all IIS.WebManager issues. I have a [PR](https://github.com/Microsoft/IIS.WebManager/pull/213) out for it. If it gets approved we could release a hotfix.

**Comment by jimmyca15** [comment]
These problems have been addressed in the latest [hotfix](https://github.com/Microsoft/IIS.WebManager/pull/213) for manage.iis.net. Please let us know if any further issues arrive.
