### ISSUE TITLE
Hostable Web Core enabled not explained enough

### ISSUE THREAD

**Issue by MaherJendoubi** [Microsoft/IIS.Administration#2]
Hi,
Would you please explain how to configure Hostable Web Core enabled as mentioned in requirements?
Thank you

**Comment by jimmyca15** [comment]
Currently Hostable Web Core (HWC) is only required for the published application. We will be open sourcing another component and until that is done the application can only be run in dev mode.

When we enable the publish scenario the HWC configuration should be transparent. It uses an applicationHost.config file like the full IIS and IIS Express. The default configuration should be acceptable in most cases.

**Comment by MaherJendoubi** [comment]
Thank you for the feedback 👍
