### ISSUE TITLE
Service installs with an unquoted service path (CWE-428)

### ISSUE THREAD

**Issue by jgregmac** [microsoft/IIS.Administration#209]
A recent Nessus scan of a new IIS Administration install reported the presence of the old unquoted service path vulnerability, as documented in the CWE database, item 428:
https://cwe.mitre.org/data/definitions/428.html

Any path contained within a service execution that that contains spaces should be properly contained within quotation marks.  Quotation marks prevent a local attacker from inserting arbitrary executables into the service path and co-opting the intended function of the service.

As an example, I was able to prevent the IIS administration service from starting by copying "notepad.exe" to "C:\Program.exe".  I then restarted the IIS administration service, and it failed to come back up.  After altering the service "Path" with quotation marks around the "C:\Program Files" element, I then was able to start the service back up.

This is not a huge security issue, but it should be trivial to fix, and it will save a lot of trouble for those of us who work in compliance-sensitive environments.

**Comment by aaronk1** [comment]
Any update on this one, @jimmyca15 ?  Still seeing same issue on IIS Administration 2.3.0 .

**Comment by aaronk1** [comment]
@shhsu this one I'm seeing security failures on also

**Comment by yaqiyang** [comment]
Fixed in v6.0.0
