### ISSUE TITLE
HttpClient example authentication

### ISSUE THREAD

**Issue by RobGibbens** [Microsoft/IIS.Administration#21]
The **README.md** gives this example for using HttpClient: 
`var apiClient = new HttpClient();`
but after a clean install of the tool, that did not work (401 Unauthorized).  I had to change it to:

```
var httpClientHandler = new HttpClientHandler()
    {
        Credentials = new NetworkCredential(userName, password, domain)
    };
var apiClient = new HttpClient(httpClientHandler);
```

Should the **README** be updated to include that, or instructions on changing the authentication mechanism, or am I doing something wrong?

**Comment by jimmyca15** [comment]
This should be updated in the README. The windows authentication requirement can be removed, but since it is the default we should have it in the example.
