### ISSUE TITLE
"Don't let this page create more messages" checkbox for Confirm()

### ISSUE THREAD

**Issue by jhkimnew** [microsoft/IIS.Administration#210]
The confirm() function shows "Don't let this page create more messages" checkbox only for Edge. This can be problematic because we need the return value of the confirm() to decide the next action. 
I'd like to suggest to implement our own confirm() function instead of using the built-in one in Jquery library.

Repro steps.

1. Open IIS.Webmanager page
2. Create a new key
3. Click refresh button of the newly created key and you will see the warning message which was created by the Confirm() function
4. The "Don't let this page create more messages" checkbox will be shown if you try to click the refresh button

NOTE: 

1. Chrome does not show the checkbox.
2. The confirm message box has also an accessibility issue. So we can fix the accessibility issue together with replacing the confirm() with our own function.

**Comment by yaqiyang** [comment]
Closed. New features are not going to be implemented in the near future
