### ISSUE TITLE
We should show a "loading..." message while opening/creating token key

### ISSUE THREAD

**Issue by jhkimnew** [microsoft/IIS.Administration#211]
In the below repro step scenarios, it requires some time to load key information but the current UI does not indicate the loading time. So, users can be confused. We should show "loading..." message and change the cursor until loading is completed.

Repro steps:
1. Open IIS.Administration
2. Click "ACCESS KEYS" menu
or, create a new key
or, refresh an existing key

**Comment by yaqiyang** [comment]
Closed. New features are not going to be implemented in the near future
