### ISSUE TITLE
When Back button is selected, we should not show the tokenForm again

### ISSUE THREAD

**Issue by jhkimnew** [microsoft/IIS.Administration#212]
Repro steps.

1. Open IIS.Administration page
2. Create a new key or refresh the existing key to open the tokenForm
3. When the tokenForm is shown, click "Got it" button to close the form
4. Click Back button of browser

EXPECTED:

The tokenForm should not be shown

ACTUAL:

The tokenForm is shown again

**Comment by yaqiyang** [comment]
Closed. New features are not going to be implemented in the near future
