### ISSUE TITLE
"Could not start service" WinServer 2012

### ISSUE THREAD

**Issue by ilzlsm** [microsoft/IIS.Administration#215]
PS C:\Users\Administrator> E:\Websites\IIS.Administration\setup\setup.ps1

位于命令管道位置 1 的 cmdlet setup.ps1
请为以下参数提供值:
Command: install
Checking installation requirements
Installation Requirements met
Copying files
[SC] CreateService 成功
Rolling back
Rolling back service creation
Rolling back HTTP.Sys port binding
Rolling back setup config creation
Rolling back SSL certificate creation
Rolling back logs folder creation
Rolling back installation folder creation
Finished rolling back.
E:\Websites\IIS.Administration\setup\setup.ps1 : Could not start service
所在位置 E:\Websites\IIS.Administration\setup\install.ps1:446 字符: 9
+         throw "Could not start service"
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
所在位置 行:1 字符: 1
+ E:\Websites\IIS.Administration\setup\setup.ps1
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], RuntimeException
    + FullyQualifiedErrorId : System.Management.Automation.RuntimeException,setup.ps1

**Comment by jimmyca15** [comment]
What versions of .NET Core do you have installed? You should be able to check like this:

```
c:\src\repos\AppConfigService>dir "c:\Program Files\dotnet\host\fxr"
 Volume in drive C is OSDisk
 Volume Serial Number is AC78-FB35

 Directory of c:\Program Files\dotnet\host\fxr

10/23/2018  11:42 AM    <DIR>          .
10/23/2018  11:42 AM    <DIR>          ..
02/15/2018  05:27 PM    <DIR>          1.0.5
01/09/2017  01:31 PM    <DIR>          1.1.0
11/03/2017  01:19 PM    <DIR>          2.0.0
11/21/2017  09:47 AM    <DIR>          2.0.3
02/23/2018  09:24 AM    <DIR>          2.0.5
03/20/2018  08:08 AM    <DIR>          2.0.6
04/13/2018  09:28 AM    <DIR>          2.0.7
08/06/2018  12:03 PM    <DIR>          2.0.9
07/09/2018  07:31 AM    <DIR>          2.1.1
08/06/2018  12:02 PM    <DIR>          2.1.2
10/23/2018  11:42 AM    <DIR>          2.1.5
               0 File(s)              0 bytes
              13 Dir(s)  19,402,866,688 bytes free
```
