### ISSUE TITLE
broken link in EULA of setup

### ISSUE THREAD

**Issue by jhkimnew** [microsoft/IIS.Administration#216]
![image](https://user-images.githubusercontent.com/20650163/49317311-ce711280-f4a8-11e8-937f-8606220111f8.png)

See the link of https://privacy.microsoft.com/en-us/privacystatement. You can see the link is displayed in broken state after the next statement. 

```
use in the help documentation and the privacy statement at https://privacy.microsoft.com/en-us/privacystatement.  http://go.microsoft.com/fwlink/?LinkID=528096Your use
```

**Comment by yaqiyang** [comment]
Fixed. The EULA has been updated
