### ISSUE TITLE
Error: Invalid Parameter when creating a new site

### ISSUE THREAD

**Issue by ddivita** [microsoft/IIS.Administration#217]
When I try to create a new site via the API i get this error:
```
400 error
{
    "title": "Invalid parameter",
    "name": "binding.binding_information",
    "status": "400"
}
```

This is the JSON being passed (very similar to the [documentation](https://docs.microsoft.com/en-us/iis-administration/api/sites))

```
{
    "name": "Demonstration Site 2",
    "physical_path": "e:\\mysites\\demosite2",
    "bindings": [
        {
            "protocol": "HTTP",
            "port": "6081",
            "ip_address": "*"
        }
    ]
}

```

I have to add in the `binding_information`, but i lose the ability to see the `port `and `ip_address` properties:

```
"name": "Demonstration Site 2",
    "id": "CAD63BDoJSnZ_RERbcbcHw",
    "physical_path": "e:\\mysites\\demosite2",
    "key": "14",
    "status": "stopped",
    "server_auto_start": "true",
    "enabled_protocols": "http",
    "limits": {
        "connection_timeout": "120",
        "max_bandwidth": "4294967295",
        "max_connections": "4294967295",
        "max_url_segments": "32"
    },
    "bindings": [
        {
            "protocol": "HTTP",
            "binding_information": "*:6081:"
        }
    ],
```

I can hack it together with splitting by the : in the value, but i don;t understand why I have to supply that property.

**Comment by ddivita** [comment]
Might want to also update the documentation since it is capitalized.  That seemed to fix it, though. Thanks!

**Comment by Rich-Lang** [comment]
https://github.com/MicrosoftDocs/IIS.Administration-docs/pull/15
