### ISSUE TITLE
Install vc++ 2015

### ISSUE THREAD

**Issue by naphtalidavies** [microsoft/IIS.Administration#227]
Hi,
While trying to install version 2.2 I get an error "microsoft visual c++ 2015 redistributable must be installed".
When trying to install it I get an error saying another version in installed. I have 2017 version installed. I do not want to uninstall 2017 for this.

**Comment by EatonZ** [comment]
C++ 2015 and 2017 are binary compatible, so you don't need to install 2015. It's possible you are just missing the 32bit or 64bit 2017 version. Make sure both are installed.

**Comment by naphtalidavies** [comment]
I have both versions of 2017 installed (32 and 64 bit). I also have versions 2013, 2012 and 2008.
But I can't install iis.administration because it requires version 2015, which can't be installed because another version is installed.

**Comment by EatonZ** [comment]
2017 should be sufficient. It's probably a bugged requirements check. Maybe one of the developers can clarify.

**Comment by shhsu** [comment]
vs redist is no longer a requirement
