### ISSUE TITLE
Grant Builtin\Administrators group access by default

### ISSUE THREAD

**Issue by Jammers23** [microsoft/IIS.Administration#232]
Accessing IIS on a server requires administrative rights. When IIS Administration API is installed, this tool is only granting access to the current user. Why isn't Administrators given access by default?

What I would like to see is that dev/scripts/setup/config.ps1 be modified to have BUILTIN\Administrators be added to "IIS Administration API Owners"

Add this line after line 125:
.\security.ps1 EnsureLocalGroupMember -AdPath "BUILTIN\Administrators" -Name $groupName -Description $groupDescription

Maybe there is a better way to give Administrators access by default, but to my knowledge, appsettings.json is what handles the access to this tool.

Thanks.

**Comment by yaqiyang** [comment]
Closed. New features are not going to be implemented in the near future
