### ISSUE TITLE
Installer needs .NET Core 1.0.7?

### ISSUE THREAD

**Issue by Jammers23** [microsoft/IIS.Administration#233]
In testing IIS Administration 2.2.1, the MSI looks only for .NET Core 1.0.7. Even if I have .NET Core 1.0.12 installed, the MSI will still require .NET Core 1.0.7 to be installed. Couldn't the installer look for a pre-installed 1.0.x version in order to skip the .NET Core installation within the MSI?

To get around this, I have been using the powershell scripts to install since that checks to see if dotnet.exe exists before installing.

Also, isn't .NET Core 1.0.7 out of support? Why is the MSI using that? 

![iisadministrationapi221](https://user-images.githubusercontent.com/48135183/53664422-12052500-3c2e-11e9-9807-e9c447eab851.png)

Thanks.

**Comment by shhsu** [comment]
This issue will be addressed in next release

**Comment by shhsu** [comment]
An update, due to https://github.com/dotnet/core-setup/issues/3381, for the next release, we would actually always install 2.1.9 shared runtime if it is not present

**Comment by Jammers23** [comment]
May I ask why the latest NET Core runtime (2.2) is not being used?

**Comment by shhsu** [comment]
@Jammers23 
.NET core runtime 2.1 is LTS. It will be supported even after 2.2 expires
