### ISSUE TITLE
Refactor project files and reuse TargetFramework build property

### ISSUE THREAD

**Issue by shhsu** [microsoft/IIS.Administration#240]
In https://github.com/Microsoft/IIS.Administration/pull/239, I tried 

1. put `TargetFramework` property in `plugins.props`
2. Declare a variable `IISAdministrationTargetFramework` in `plugins.props`.

When running dotnet restore, both scenarios run into the same error:
```C:\Program Files\dotnet\sdk\2.1.603\NuGet.targets(119,5): error : Invalid framework identifier ''.```

Looks like dotnet restore does not know how to resolve project imports. Refactoring seems not possible

We should try and investigate why it is so we can have a single point of truth for `TargetFramework` across projects

**Comment by yaqiyang** [comment]
Closed. New features are not going to be implemented in the near future
