### ISSUE TITLE
Chrome fails to authenticating a domain user

### ISSUE THREAD

**Issue by jhkimnew** [microsoft/IIS.Administration#245]
1. Login with domain user such as foodomain\foouser
2. Install the latest build
3. Start Chrome
4. Browse https://manage.iis.net
5. You will see the prompt of user
6. Type the domain user and password

EXPECTED:

Works

ACTUAL:

The prompt box is shown again

NOTE:

If use a local user instead of domain user, there is no problem.

Here is how to test with a local user.
a) add a local admin user onto the IIS Administration API Owners group
b) restart Chrome and do the repro with using the local user instead of the current login user.

**Comment by yaqiyang** [comment]
Closed. New features are not going to be implemented in the near future
