### ISSUE TITLE
Few questions on Security

### ISSUE THREAD

**Issue by StephenShamakian** [Microsoft/IIS.Administration#26]
1. Is there a way we can change the binding information (ip/port/cert) for the API itself? If so how is that done?

2. How does one customize the security? It looks like the API requires both Access Tokens and Windows IDs. Why the extra access tokens if protected with Windows Auth?

3. Not necessarily a security question. But how often will this be updated? Trying to figure out how to keep this up-to-date on many servers in a consistent way.

**Comment by jimmyca15** [comment]
@RedTechie 

1. This behavior is possible and in the future we plan on making it something that can be easily configured. As of now there is no way to do it through the MSI or the PowerShell setup script. The API uses an applicationHost.config file, so this can be edited to change the binding information. However, changing the binding also requires remapping the SSL certificate to the new port. The cert can be switched out for a trusted cert and this is what we recommend for remote access of the API. We are working on the documentation for this as well. Changing out the cert/mapping it to a new port requires using the netsh command line tools. 

2. Access tokens are the backbone of the API security. The windows authentication is a layer on top that we add in to be able to restrict access to Administrators + IIS Administrators only. Windows authentication can be removed from the API, which means only an access token would be required. This makes the process of connecting to the API from a client, such as https://manage.iis.net, easier, but it also means anyone with an access token can configure your webserver. I personally remove the windows authentication requirements that way I can access the API from my mobile device easier. It is just a matter of keeping the access token secure. 

If you go to C:\Program Files\IIS Administration\<version>\Microsoft.IIS.Administration\web.config you can see how the windows authentication is configured. 

**note:** The windows authentication for generating the access tokens should not be removed.

3. The next release will come with a new MSI which will perform an update of the API. If you use the PowerShell script to install then the PowerShell script will perform the update. However, the MSI and the PowerShell script installation methods shouldn't be mixed. 

We recommend using the MSI, that isn't an option on Nano Server though. Making sure the latest MSI is installed is the key to being up to date. Right now we only have one preview release MSI.

**Comment by RedTechie** [comment]
Thanks! For the detailed responses! I have a few more follow-up questions:

Thanks for the info on the bindings!

Regarding point 2. So how would that work for managing say thousands of servers? I would figure Windows auth would be better as that uses AD based authentication vs. local based authentication (access tokens). Is there a way we can only use Windows auth vs. access tokens?

Regarding point 3. If we installed it through the link on manage.iis.net is that the msi version or the powershell version? Also I haven't checked so it may already have this ability, but is their an option for a silent install so we can push this out via automation and/or package deployment tools?

**Comment by drago-draganov** [comment]
@RedTechie 

These are great questions!

#2
Let me first elaborate on the need of Access Token as absolute minimum basic security.  The IIS Administration API is HTTP based (REST Api). That makes it accessible from almost every type of client, and that includes browser (like manage.iis.net). Any type of implicit authentication (Windows Authentication, Client Cert, Cookie, etc.) in a browser is subject to Cross-site Request Forgery Attacks (XSRF Attacks). To eliminate that the caller should explicitly provide a secret. Access Tokens serve that purpose. In addition they replace basic http authentication as stronger form (higher entropy) than simple username/password. 

Now to the question:
When the API generates Access Token, it stores a hash of it (and a bit more details) in a file (...\Program Files\IIS Administration\<version>\Microsoft.IIS.Administration\config\api-keys.json). If you copy an entry from "keys" and add it to different server api-keys.json file, it will allow exactly the same Access Tokens to proceed. If your prefer the system to rely on Integrated Authentication all alone, then generate an Access Token and distribute it's corresponding key entry into each deployment api-keys.json. (you can also copy the entire file, though I would not recommend). Then use that Access Token with each of your servers. Or perhaps cluster them in groups - the choice is yours.

The IIS Administration API is a pure Web Application, powered by IIS (it just runs as micro-service). As such you can customize it with any IIS security feature (Windows Authentication, Client Certificate Mapping, Url Authorization, IP Restrictions, etc.). I'm sure these config will sound familiar:
...\Program Files\IIS Administration\<version>\host\applicationHost.config
...\Program Files\IIS Administration\<version>\Microsoft.IIS.Administration\web.config

We are aware that each organization has unique requirements. Our goal was to enable you to control and customize your own security policy via already well-known config. We are going to explain these in separate blog post in greater details.

#3 
The installer coming from manage.iis.net is the MSI in question (packed as a bundle, hence the EXE). It actually invokes under the hood the same PowerShell setup that someone could use alone. We need the PowerShell option for environments that don't support MSI (i.e. Nano Server - https://blogs.iis.net/adminapi/microsoft-iis-administration-on-nano-server)

The installer supports unattended mode. You should be able to use it with your automation.

On manage.iis.net we will always provide the latest version. We also plan to add notification there if newer version is available.

**Comment by RedTechie** [comment]
Great thanks for the information! This actually helps a lot!
