### ISSUE TITLE
When accessing token page, user sees 401 error even though the user is in administrative subgroup

### ISSUE THREAD

**Issue by shhsu** [Microsoft/IIS.Administration#261]
This issue is intermittently reproducible.

* User would install IIS.Administration, the setup creates "IIS Administration Owners" local group and add the installation user in the group
* User tries to create API token, receive 401 response instead

Problem:
User's Windows Authentication token as not updated. Any time [GetTokenInformation](https://docs.microsoft.com/en-us/windows/desktop/api/securitybaseapi/nf-securitybaseapi-gettokeninformation) is called. The claim entry declaring the user belonging to "IIS Administration Owners" would not be populated.

Workaround:
* Solution 1: Log the user out and back in again
* Solution 2: In theory [Invoke-GPUpdate](https://docs.microsoft.com/en-us/powershell/module/grouppolicy/invoke-gpupdate?view=win10-ps) should work but when I tried it, it didn't quite work.

Possible fix:
Installer to add the currently user directly to the config file, same behavior as `2.2.0` and below

**Comment by shhsu** [comment]
A workaround is being looked into. We can potentially allow token to be issues if the current user is an local administrator of the server.

However, looks like `WindowsPrincipal.IsInRole(WindowsBuiltInRole.Administrator)` always return false.
List of claims in the context includes the administrator sid is flaged as `DenyOnlySid`

**Comment by yaqiyang** [comment]
Closed. New features are not going to be implemented in the near future
