### ISSUE TITLE
Better handle unexpected exception if uninstall failed

### ISSUE THREAD

**Issue by shhsu** [Microsoft/IIS.Administration#262]
If uninstaller threw unexpected exception, the user would still see "Uninstall successful" but in fact the resource are not properly cleaned up.
Things that can potentially get left behind are 
* Self singed cert
* Cert binding
* Service "Microsoft IIS Administration"
* Program files directory

**Comment by yaqiyang** [comment]
Closed. New features are not going to be implemented in the near future
