### ISSUE TITLE
More granular devSetup

### ISSUE THREAD

**Issue by shhsu** [Microsoft/IIS.Administration#265]
Currently, to test a environment with IIS Administration API already installed, user would call `**.\build.ps1 -devSetup -test -verbose**`

The `devSetup` flag can be considered a overkill becuase all we want is the config files to be populated.

**Comment by shhsu** [comment]
One problem we encountered is that `devSetup` can fail if .NET framework 3.5 is not installed

**Comment by yaqiyang** [comment]
Closed. New features are not going to be implemented in the near future
