### ISSUE TITLE
Setup failed 0x80070643 on Windows server 2008 R2

### ISSUE THREAD

**Issue by ahdung** [Microsoft/IIS.Administration#274]
Please help, thanks.

![微信截图_20190717160841](https://user-images.githubusercontent.com/12094247/61358566-2d0ac580-a8ad-11e9-9abe-47e803f83c41.png)

[Microsoft_IIS_Administration_2.3.0_20190717155723.log](https://github.com/microsoft/IIS.Administration/files/3400788/Microsoft_IIS_Administration_2.3.0_20190717155723.log)

**Comment by shhsu** [comment]
Sorry for the delay, unfortunately this file doesn't have enough information.
Can I have the different log file from the temp directory `Microsoft_IIS_Administration_2.3.0_20190717155723_iis_administration_msi.log`. It should have more information that is relevant

**Comment by shhsu** [comment]
Also please search in Event Viewer and see if you can find any application level log for `Microsoft IIS Administration API` especially around the time of installation.

**Comment by ahdung** [comment]
Thank you, here you are, and no any source == `Microsoft IIS Administration API` event.

[Microsoft_IIS_Administration_2.3.0_20190717155723_000_iis_administration_msi.zip](https://github.com/microsoft/IIS.Administration/files/3424520/Microsoft_IIS_Administration_2.3.0_20190717155723_000_iis_administration_msi.zip)

**Comment by shhsu** [comment]
This issue is different from #275. Looks like some component might be missing. The application was installed but not able to start.

Is this a upgrade or a new install?

**Comment by shhsu** [comment]
Also, can you confirm that your OS is above (Windows Server: 2008 R2 SP1+) and supported by .NET core 2.1?

**Comment by ahdung** [comment]
@shhsu My case is install not success, not can't start, and is new install not upgrade. This is my env:
![微信截图_20190725095159](https://user-images.githubusercontent.com/12094247/61839905-ee36ca00-aec1-11e9-9c50-41d56cf4f2a1.png)

On another with same OS pc, install and work all fine.
I tried: reboot + reinstall .net core runtimes.

**Comment by shhsu** [comment]
As far as I know, sometimes our uninstall script would left the old install directory behind. Most likely because we have played around with files ownership and permission a bit too much. This can cause the issue you are describing during upgrade. To workaround the issue. Please try the following.

* Ensure IIS Administration is uninstalled and no longer present in your "Programs and Features/程序和功能 menu"
* Open elevated command prompt, run `rmdir "C:\Program Files\IIS Administration" /s /q`
* Try installing again

**Comment by ahdung** [comment]
@shhsu Nono, i never success install it on this pc, so i think it's not abount uninstall thing, actually here is no "IIS Administration" in P&F, and not exists `"C:\Program Files\IIS Administration"` dir, `Program Files (x86)` too.
You know chinese lang, that's great ^_^

**Comment by shhsu** [comment]
Sorry for misunderstanding. I think this means there is not enough information for us to debug why the service was installed and not started. (Therefore it reverted back)
I have created a item and we will try to push a fix so we can diagnose the issue better

https://github.com/microsoft/IIS.Administration/issues/278

**Comment by shhsu** [comment]
I presume the issue still exists? With https://github.com/microsoft/IIS.Administration/pull/283 We will be able to diagnose the issue better. Would you like use to push a hotfix?

**Comment by ahdung** [comment]
@shhsu I agree, so what should I do?

**Comment by shhsu** [comment]
[IISAdministrationSetup.zip](https://github.com/microsoft/IIS.Administration/files/3499427/IISAdministrationSetup.zip)
Here is a hotfix that has better logging. Hopefully we will catch the error this time.
Also, in case this does't work. Can you also tell me your dotnet version
`"%programfiles%\dotnet\dotnet" --version`

**Comment by ahdung** [comment]
@shhsu still setup failed, same error message and code.
`"%programfiles%\dotnet\dotnet" --version` is `2.2.108`
if you need some logs, just tell me.

**Comment by shhsu** [comment]
@ahdung 
That's expected, but you should see some error in your event logs correct? Please check application event log for `Microsoft IIS Administration API`

**Comment by ahdung** [comment]
@shhsu logs content:
```
[0FE0:0F0C][2019-08-14T09:45:10]i301: Applying execute package: iis_administration_msi, action: Install, path: C:\ProgramData\Package Cache\{1A93BF06-C31E-4005-A54F-5771672454A8}v2.3.0\packages\iis_administration.msi, arguments: ' ARPSYSTEMCOMPONENT="1" MSIFASTINSTALL="7" INSTALLFOLDER="" VSEXTUI="1" DEFAULT_CORS="true"'
[0FE0:0F0C][2019-08-14T09:45:37]e000: Error 0x80070643: Failed to install MSI package.
[0FE0:0F0C][2019-08-14T09:45:37]e000: Error 0x80070643: Failed to execute MSI package.
[0F18:039C][2019-08-14T09:45:37]e000: Error 0x80070643: Failed to configure per-machine MSI package.
```
in application event logs, no `Microsoft IIS Administration API`, just `MsiInstaller`, said: `Product: Microsoft IIS Administration -- Installation failed.`

This is a install issue, but you sir looks like think it's a start Service issue.

**Comment by shhsu** [comment]
After the installer installed all the files, it check if the service starts. If not it would tell the OS installation fails.
This is present in your previous iis_administration_msi.log
```
CAQuietExec64:  ????: Start-Service for Microsoft IIS Administration started.
CAQuietExec64:  Start-Service : ????????????"Microsoft IIS Administration (Microsoft IIS Admini
CAQuietExec64:  stration)": ???????"."???? Microsoft IIS Administration?
CAQuietExec64:  ???? C:\Program Files\IIS Administration\2.3.0\setup\install.ps1:60 ??: 30
CAQuietExec64:  +                 Start-Service <<<<  -name $name
CAQuietExec64:      + CategoryInfo          : OpenError: (System.ServiceProcess.ServiceControl 
CAQuietExec64:     ler:ServiceController) , ServiceCommandException
CAQuietExec64:      + FullyQualifiedErrorId : CouldNotStartService,Microsoft.PowerShell.Comman 
CAQuietExec64:     ds.StartServiceCommand
CAQuietExec64:   
CAQuietExec64:  ????: Checking the current status. Status: Stopped
CAQuietExec64:  ??: Get-Service does not return Running. Status: Stopped
CAQuietExec64:  ????: Retrying to call Start-Service for Microsoft IIS Administration.
CAQuietExec64:  Start-Service : ????????????"Microsoft IIS Administration (Microsoft IIS Admini
CAQuietExec64:  stration)": ???????"."???? Microsoft IIS Administration?
CAQuietExec64:  ???? C:\Program Files\IIS Administration\2.3.0\setup\install.ps1:72 ??: 34
CAQuietExec64:  +                     Start-Service <<<<  -name $name
CAQuietExec64:      + CategoryInfo          : OpenError: (System.ServiceProcess.ServiceControl 
CAQuietExec64:     ler:ServiceController) , ServiceCommandException
CAQuietExec64:      + FullyQualifiedErrorId : CouldNotStartService,Microsoft.PowerShell.Comman 
CAQuietExec64:     ds.StartServiceCommand
CAQuietExec64:   
CAQuietExec64:  ????: StartService failed. Retrying in 1 seconds. Error: Unexpected status: 
CAQuietExec64:  Stopped
CAQuietExec64:  ????: Checking the current status. Status: Stopped
CAQuietExec64:  ??: Get-Service does not return Running. Status: Stopped
????: StartService failed. Retrying in 1 seconds. Error: Unexpected status: 
CAQuietExec64:  Stopped
CAQuietExec64:  ????: Checking the current status. Status: Stopped
CAQuietExec64:  ??: Get-Service does not return Running. Status: Stopped
??: StartService failed the maximum number of 2 times. Error: Unexpected 
CAQuietExec64:  status: Stopped
CAQuietExec64:  Rolling back
```
This means that the install was almost complete but the service does not start and the installer end up claiming the install failed and roll back

If there is no application log this means the application even fails to load.

**Comment by shhsu** [comment]
@ahdung 
Can you take a look at `Visual C++ Redistributable` and see if it is missing on failure machine and present on the successful machine.

**Comment by ahdung** [comment]
@shhsu Thanks for describe. I look `Microsoft_IIS_Administration_2.3.0_20190814094506_000_iis_administration_msi.log`, there is no `Start-Service`, it is:
```
MSI (s) (F4:80) [09:45:12:529]: Executing op: CustomActionSchedule(Action=CA_PSINSTALL,ActionType=1025,Source=BinaryData,Target=CAQuietExec64,CustomActionData="PowerShell.exe" -NonInteractive -NoLogo -InputFormat None -NoProfile -ExecutionPolicy Bypass -Command "& 'C:\Program Files\IIS Administration\2.3.0\setup\msi-setup.ps1' Install -Verbose -Path 'C:\Program Files\IIS Administration\' -Version '2.3.0'" -IncludeDefaultCors:$true)
MSI (s) (F4:E0) [09:45:12:529]: Invoking remote custom action. DLL: C:\Windows\Installer\MSI6BAB.tmp, Entrypoint: CAQuietExec64
MSI (s) (F4:58) [09:45:12:529]: Generating random cookie.
MSI (s) (F4:58) [09:45:12:529]: Created Custom Action Server with PID 1880 (0x758).
MSI (s) (F4:08) [09:45:12:544]: Running as a service.
MSI (s) (F4:08) [09:45:12:544]: Hello, I'm your 32bit Impersonated custom action server.
CAQuietExec64:  Active code page: 437
CAQuietExec64:  ????: Verifying user is an Administrator
CAQuietExec64:  ????: Ok
CAQuietExec64:  ????: Verifying user is an Administrator
CAQuietExec64:  ????: Ok
CAQuietExec64:  Checking installation requirements
CAQuietExec64:  ????: Ok
CAQuietExec64:  ????: .NET 3.5 required for setup to continue
CAQuietExec64:  ????: Verifying NetFx3 is Enabled
CAQuietExec64:  ??: NetFx3 not enabled
CAQuietExec64:  Enabling NetFx3 (.NET Framework 3.5)
CAQuietExec64:  ????: Ok
CAQuietExec64:  ????: Verifying .NET Core shared framework installed
CAQuietExec64:  ??: .NET Core Shared Framework not installed
CAQuietExec64:  ??: Download the .NET Core Runtime (LTS) 
CAQuietExec64:  'https://www.microsoft.com/net/download/core#/runtime'
CAQuietExec64:  Rolling back
CAQuietExec64:  Finished rolling back.
CAQuietExec64:  Write-Error : .NET Core required to continue
CAQuietExec64:  ???? C:\Program Files\IIS Administration\2.3.0\setup\require.ps1:41 ??: 14
CAQuietExec64:  +         throw <<<<  ".NET Core required to continue"
CAQuietExec64:  ???? C:\Program Files\IIS Administration\2.3.0\setup\msi-setup.ps1:186 ??: 16
CAQuietExec64:  +     Write-Error <<<<  -Exception $_.exception -Message $($_.Exception.Message
CAQuietExec64:   + ::NewLine + $_.InvocationInfo.PositionMessage)
CAQuietExec64:      + CategoryInfo          : NotSpecified: (:) , RuntimeExceptio 
CAQuietExec64:     n
CAQuietExec64:      + FullyQualifiedErrorId : System.Management.Automation.RuntimeException,Mi 
CAQuietExec64:     crosoft.PowerShell.Commands.WriteErrorCommand
CAQuietExec64:  Error 0x80070001: Command line returned an error.
CAQuietExec64:  Error 0x80070001: QuietExec64 Failed
CAQuietExec64:  Error 0x80070001: Failed in ExecCommon64 method
CustomAction CA_PSINSTALL returned actual error code 1603 (note this may not be 100% accurate if translation happened inside sandbox)
```
looks like error is about downloading, but can't see installation need what version of runtime, please help.
[Microsoft_IIS_Administration_2.3.0_20190814094506_000_iis_administration_msi.log.zip](https://github.com/microsoft/IIS.Administration/files/3507670/Microsoft_IIS_Administration_2.3.0_20190814094506_000_iis_administration_msi.log.zip)

**Comment by shhsu** [comment]
That is odd.. This error log is different from before.
Let's try manually install .NET Core 2.1 and ASP.NET core 2.1. (If they are already installed, uninstall first) Please install both of the following. Note that we need 2.1 not 2.2. because 2.1 is LTS and will be supported for longer term, but if you already have 2.2 you do no have to uninstall 2.2. They can both be present in your system

https://dotnet.microsoft.com/download/thank-you/dotnet-runtime-2.1.12-windows-x64-installer

https://dotnet.microsoft.com/download/thank-you/dotnet-runtime-2.1.12-windows-x64-asp.net-core-runtime-installer

**Comment by ahdung** [comment]
@shhsu I tried to installed 2.1, but log still say `.NET Core Shared Framework not installed`:
![微信截图_20190817084709](https://user-images.githubusercontent.com/12094247/63204578-d2db6b00-c0cb-11e9-9a58-6d936d9a3a37.png)

But here have little different, in `20190814094506` log is:
`CAQuietExec64:  ??: .NET Core Shared Framework not installed`
in `20190817084140` is:
`??: .NET Core Shared Framework not installed`, no `CAQuietExec64:` prefix.

**Comment by shhsu** [comment]
Those errors are the same. They both could occur when `Get-Command "dotnet.exe"` does not point to `Join-Path $env:ProgramFiles "dotnet\dotnet.exe"`

I am not exactly sure why the logic was there. There shouldn't be a requirement that the dotnet.exe needs to be there. Can you confirm if your dotnet.exe is there? If not, can you modify your `PATH` to ensure your dotnet.exe points there

**Comment by ahdung** [comment]
I'm not sure what your meaning, so please look picture:

![微信截图_20190820101436](https://user-images.githubusercontent.com/12094247/63312213-5b0f7980-c333-11e9-8b68-211af154a970.png)

**Comment by zake0204** [comment]
![image](https://user-images.githubusercontent.com/65229760/83852277-2182f000-a746-11ea-8017-1a8c89c71d4f.png)
![image](https://user-images.githubusercontent.com/65229760/83852394-4a0aea00-a746-11ea-938e-f74585d0e929.png)

![image](https://user-images.githubusercontent.com/65229760/83852442-5a22c980-a746-11ea-91cc-9e3d4fbd7d51.png)

**Comment by v-JeanWANG** [comment]
It looks like the installation of IIS Administration API failed since the verify logic in https://github.com/microsoft/IIS.Administration/blob/dev/scripts/setup/require.ps1 is wrong when 'Get-Command "dotnet.exe"' returns 2 items, which happens on your machine.

Try reinstall your .NET and make sure 'Get-Command "dotnet.exe"' returns only ONE item.

If that's the root cause, then it looks like a defect in IIS Administration API setup process.

**Comment by ahdung** [comment]
@v-JeanWANG Thank you, you inspired me. The problem may not on dotnet, but on powershell. So I upgraded powershell to 4.0, then `get-command "dotnet.exe"` returned only one record, and I tried to install IIS Admin again, it succeeded. Thank you very much.

But there is another issue, please help. #295
