### ISSUE TITLE
Remove expired access tokens

### ISSUE THREAD

**Issue by shhsu** [Microsoft/IIS.Administration#279]
IIS Web Manager create session based short lived (3 days) token
https://github.com/microsoft/IIS.WebManager/blob/dev/src/app/resources/scripts/iis_scripts/Get-Token.ps1

It would be cleaned up if the app is gracefully destroyed but otherwise the token would be left in the api-keys file.

We should remove expired token.

**Comment by yaqiyang** [comment]
Closed. New features are not going to be implemented in the near future
