### ISSUE TITLE
Feature Request: File System Endpoint

### ISSUE THREAD

**Issue by StephenShamakian** [Microsoft/IIS.Administration#28]
This API pretty much covers everything one needs to manage IIS without having to RDP into the server (Certs, IIS Functions, etc.)! Love it!

But one glaring omission is managing the file system (creating a folder to store an IIS site files or an application. We still need to remotely access the server either through RDP or UNC to do this. It would be awesome if there was a third forth endpoint for file system CRUD operations.

If the API had that functionality one could fully manage IIS servers through this interface.

**Comment by drago-draganov** [comment]
@StephenShamakian 

This is a work item on our plate. File access will be provided at the API level, as well as accessible via the web user interface. Thanks for looking into!

**Comment by drago-draganov** [comment]
I'm glad to announce the support for File System endpoint with the release of 1.0.38 - [Release Notes](https://github.com/Microsoft/IIS.Administration/releases)
For more information, please refer the blog post [Introducing the Files API](https://blogs.iis.net/adminapi/iis-administration-preview-1-0-38-introducing-the-files-api)
