### ISSUE TITLE
What is the correct way to renew SSL cert?

### ISSUE THREAD

**Issue by martyn-tf** [Microsoft/IIS.Administration#284]
The SSL cert we were using with the MS IIS Admin Service expired. To fix it (and this was prob a mistake) I thought I could delete it and recreate manually. This didnt work as expected.

I have now reinstalled / upgraded the service to 2.3.0. 

This created a new cert called MS Administration Server Certificate that will expire in 2021.

However, I can start the Windows service but when I try to access the site on https://localhost:55539 I see a "This site can’t be reached. The connection was reset." message. Everytime I access the url I see an error in the system log.

"An error occurred while using SSL configuration for endpoint 0.0.0.0:55539.  The error status code is contained within the returned data."

On the details tab I see

In Words

0000: 00040000 00300002 00000000 C0003AAD 
0010: 00000000 00000000 00000000 00000000 
0020: 00000000 00000000 C000005F 

How can I reconfigure the SSL so that works correctly with the service? I am hoping that I can use one of the PS scripts or something.

Any pointers would really help.

FYI this is on Windows 2012.

**Comment by martyn-tf** [comment]
If i run

.\cert.ps1 Get-LatestIISAdminCertificate

It does return a certificate and the thumbprint matches the certificate I see in certificate management.

**Comment by shhsu** [comment]
Can you try uninstalling again using 2.3.0. The new uninstaller should clean up site cert/binding information
