### ISSUE TITLE
centralized certificate store support on binding

### ISSUE THREAD

**Issue by dolphinsd** [Microsoft/IIS.Administration#285]
there is not way in user interface to create binding and set it to use central certificate store like in iis interface attached

![central bind](https://user-images.githubusercontent.com/3460517/64588862-7ed54680-d358-11e9-85c5-ee19fbe75413.png)

**Comment by shhsu** [comment]
For website management, please use `manage.iis.net`. If you edit a website's binding you can select a certificate from central certificate store
