### ISSUE TITLE
SSL Connection Could not established

### ISSUE THREAD

**Issue by Jzheng213** [Microsoft/IIS.Administration#288]
Hello, I am getting an Authentication Exception. Everything works locally, but when I call the API remotely I get an Authentication Exception: the remote certificate is invalid according to the validation procedure. Does IIS Administration API require additional configuration aka having to create another certificate and bind it to the port?

**Comment by shhsu** [comment]
The api installation process creates only a self signed certificate. You would not be able to access the api remotely unless you have a valid cert

**Comment by Jzheng213** [comment]
Thanks!
