### ISSUE TITLE
Cannot upgrade from 2.2.0 to 2.3.0 > 0x80070643

### ISSUE THREAD

**Issue by dobrzele** [Microsoft/IIS.Administration#292]
I'm having trouble with an upgrade from 2.2.0 to 2.3.0.  I have successfully completed the upgrade on 6 of 8 machines.  But 2 of them are failing with this message

setup failed
0x80070643 fatal error during installation

Looking at the detailed log file, I see this line:

CAQuietExec64:  C:\Program Files\IIS Administration\2.3.0\setup\msi-setup.ps1 : Cannot upgrade from 2.3.0 to 2.3.0.

Is there a way to forcibly / manually remove all remnants of version 2.3.0, and also 2.2.0?  

The 2.2.0 uninstaller is failing with the same error (0x80070643), but cannot find the setup.config file:

CAQuietExec64:  WARNING: Cannot find setup.config file for uninstall. Cannot continue
CAQuietExec64:  
At C:\Program Files\IIS Administration\2.2.0\setup\uninstall.ps1:30 char:3
CAQuietExec64:  
+         throw "Cannot find setup.config file for uninstall. Cannot co ...

Unfortunately I do not have a clean box with the old setup.config (if it exists) - all the others were upgraded!

Thank you,
Joel

**Comment by dobrzele** [comment]
**Update**: I found an old setup.config for version 2.2.0 on another server, and in desperation placed it in the install folder (C:\Program Files\IIS Administration\2.2.0).  However, now I get this error trying to uninstall 2.2.0:
CAQuietExec64:  VERBOSE: Verifying user is an Administrator
CAQuietExec64:  VERBOSE: Ok
CAQuietExec64:  Error 0xc0000409: Command line returned an error.
CAQuietExec64:  Error 0xc0000409: QuietExec64 Failed
CAQuietExec64:  Error 0xc0000409: Failed in ExecCommon64 method

The uninstall seems to delete setup.config, and I cannot uninstall 2.2.0, nor install 2.3.0.  It appears that I'm going to need to remove all remnants of 2.2.0 manually in order to proceed with 2.3.0.  But how?  Thanks.

**Comment by dobrzele** [comment]
@shhsu, do you have some ideas?

**Comment by jeffhtu** [comment]
I was getting this same exact error when installing 2.3.0. I managed to run uninstall using **PowerShell** with **elevated** privilege. After that 2.3.0 installed fine. I'm not familiar with CAQuietExec64. Perhaps use PowerShell instead. (I know, you weren't holding your breath all this time, lol)

![image](https://user-images.githubusercontent.com/7856157/106349033-9c31ea00-6298-11eb-9d60-0ee3ff2ba8d7.png)

**Comment by yaqiyang** [comment]
The installer does not support upgrade. You should uninstall older version first.
