### ISSUE TITLE
Requests from Postman always unauthorized

### ISSUE THREAD

**Issue by MostafaBelihi** [Microsoft/IIS.Administration#293]
Steps:
Installed IIS Admin Manger on a Windows Server 2012 R2 Datacenter.
Generated an access token from the web app.
Tried to make an API call using Postman to the URL https://localhost:55539/api/webserver/websites, setting a header "Access-Token" to "Bearer {api-key}.

I always get 401 Unauthorized response with a header: "WWW-Authenticate": "NTLM".

No mentioning of Postman on online guides or posts, but I think this way is correct.
Any help?

**Comment by MostafaBelihi** [comment]
Also any tries to change the appsettings.json file, to edit security settings, is not allowed even if I stop the service.

**Comment by yaqiyang** [comment]
Two possibilities. You may not be part of the users/administrators, or you don't have the files section configured correctly in appsettings.json

For users/administrators, it should look like, 
```
 "users": {
      "administrators": [
        "mydomain\\myusername",
        "myusername@mycompany.com",
        "IIS Administration API Owners"
      ],
```
For files, 
```
  "files": {
    "locations": [
      {
        "alias": "inetpub",
        "path": "C:\\inetpub",
        "claims": [
          "read",
          "write"
        ]
      },
      {
        "alias": "tests",
        "path": "C:\\Repos\\iis-admin\\.test",
        "claims": [
          "read",
          "write"
        ]
      }
    ]
  }
```
