### ISSUE TITLE
Should the API update the serverAutoStart attribute in the applicationHost.config for IIS?

### ISSUE THREAD

**Issue by ddivita** [Microsoft/IIS.Administration#296]
We are using the IIS Admin API to help manage Blue / Green deployments in IIS. The API will start or stop sites based on what state the sites are running at the time. So if site 1 is stopped and Site 2 is started, the next deployment would stop site 2 and start site 1. 

We have noticed that the API does not alter the `serverAutoStart` attribute in the applicationHost.config `<site>` definitions. If IIS is restarted it uses the applicationHost.config to determine which sites should be started / stopped. In the IIS management console, starting / stopping sites manually is persisted in the  applicationHost.config file.

```
            <site name="testsite" id="45" serverAutoStart="true">
                <application path="/" applicationPool="testsite">
                    <virtualDirectory path="/" physicalPath="C:\sites\testiste" />
                </application>
                <bindings>
                    <binding protocol="http" bindingInformation="*:80:" />
                </bindings>
            </site>
```

Is this a bug in the admin API or is this intentional?

**Comment by ddivita** [comment]
Any thoughts on this issue?

**Comment by yaqiyang** [comment]
Closed. New features are not going to be implemented in the near future
