### ISSUE TITLE
Registry key not found. Key = 'SOFTWARE\Microsoft\ASP.NET Core\Shared Framework\v2.1'

### ISSUE THREAD

**Issue by vidarfreyr** [Microsoft/IIS.Administration#297]
On a Windows server 2012 when i run the IIS_Administration_2.3.0

i get an error 

Registry key not found. Key = 'SOFTWARE\Microsoft\ASP.NET Core\Shared Framework\v2.1'
 Setting numeric variable 'ASPNET_CORE_21_SHARED_FRAMEWORK_EXISTS' to value 0

ASP,net Core is at 2.2 on the server.

Is there a way a round this ?

**Comment by yaqiyang** [comment]
This should not occur in v6.0. If a newer shared framework exists, this variable should still be false. But when it installs the older version, the process will fail and the installer will ignore it.
