### ISSUE TITLE
Readme says to go to manage.iis.net which no longer exists

### ISSUE THREAD

**Issue by rjk** [Microsoft/IIS.Administration#298]
In the "Using the new API" section of readme it says to go to manage.iis.net to get an access token. That site no longer exists. It'd be good to update this for new users who are expecting to follow the instructions to start using this new API.

**Comment by jeffhtu** [comment]
Once you have the Microsoft IIS Administration API installed, open a browser to http://localhost:55539 and from there you can request an access token.

![image](https://user-images.githubusercontent.com/7856157/106348787-e3b77680-6296-11eb-877f-b431fdd14c52.png)

**Comment by yaqiyang** [comment]
I am changing readme to point to https://iis-manage.azurewebsites.net/get
