### ISSUE TITLE
Unquoted path for Microsoft IIS Administration windows service

### ISSUE THREAD

**Issue by Jammers23** [Microsoft/IIS.Administration#299]
I have version 2.3.0 installed. Qualys vulnerability scan has flagged the path of the Microsoft IIS Administration windows service. The exact issue is that the path for dotnet.exe is not in quotes.

[Qualys ID 105484 = Windows Unquoted/Trusted Service Paths Privilege Escalation Security Issue](https://qualys-secure.force.com/discussions/s/article/000003570)

**Service Name:** 
Microsoft IIS Administration 
**Image Path:** 
C:\Program Files\dotnet\dotnet.exe "C:\Program Files\IIS Administration\2.3.0\Microsoft.IIS.Administration\Microsoft.IIS.Administration.dll" /serviceName="Microsoft IIS Administration"

To fix this, I am modifying the registry:
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\Microsoft IIS Administration
ImagePath = "C:\Program Files\dotnet\dotnet.exe" "C:\Program Files\IIS Administration\2.3.0\Microsoft.IIS.Administration\Microsoft.IIS.Administration.dll" /serviceName="Microsoft IIS Administration"

Please address this in the next version.

Thanks!

**Comment by yaqiyang** [comment]
This is fixed in version 6.0
