### ISSUE TITLE
Unable to Download

### ISSUE THREAD

**Issue by umardraz** [Microsoft/IIS.Administration#300]
Hello I am unable to download IIS Administration, when I visit this **https://manage.iis.net/** it redirect me on this new url 
**https://msft-sme.myget.org/**

**Comment by cpkuo** [comment]
I'm having the same issue. Why is it redirecting to MyGet? Has the download been unavailable for this long?

**Comment by csforbes** [comment]
Are the Release assets on Github a valid download source?

https://manage.iis.net/get forwards to https://msft-sme.myget.org/ , which upon attempting to log in, says "This application is not published by Microsoft or your organization" and the Sign Up link is for a free trial.

**Comment by cpkuo** [comment]
Yes, it appears the Github download link is the only way to download the source.

**Comment by yaqiyang** [comment]
You can download it from https://iis-manage.azurewebsites.net/get right now
