### ISSUE TITLE
Microsoft.IIS.Administration is no longer actively maintained

### ISSUE THREAD

**Issue by shirhatti** [Microsoft/IIS.Administration#305]
`Microsoft.IIS.Administration `was built using .NET Core 2.1, which reached end of life of August 21, 2021. Unfortunately, we've had to make the difficult decision to longer maintain and support Microsoft.IIS.Administration.

To make it easier to transition from `Microsoft.IIS.Administration` to a supported technology for managing IIS, we will be making one final update to target `net6.0`. This update is planned for after .NET 6 is released (expected late 2021).

**Comment by ukdtom** [comment]
Any suggestions for a supported technology for managing IIS?

**Comment by Tractivity-Jamie** [comment]
Is there any further news on when we can expect the net6.0 version to be released? 
Thank you.

**Comment by EatonZ** [comment]
@shirhatti Is no longer at Microsoft so I imagine someone else will have to take over and release the update.

**Comment by jsirianni** [comment]
Would be nice to get an update

**Comment by yaqiyang** [comment]
We have updated the dev branch to support .Net 6 and will release it soon.

**Comment by intenzive** [comment]
@yaqiyang, is it reasonable to start using this API at that point on a new project? 

Do you have any idea what will be the supported technology for managing IIS in the future?

**Comment by leecow** [comment]
@intenzive - Yes, once the update is available, the API will be running on an in-support version of .NET and is reasonable to use. After that point, we'll monitor things for a time to see if additional fixes are needed due to migrating to .NET 6. 

We're still discussing what the supported IIS management platform might be going forward and unfortunately don't have more information at this time.

**Comment by eajhnsn1** [comment]
Is there an ETA for the release which supports .NET 6?

**Comment by Pilchard123** [comment]
Is there any update here?

**Comment by yaqiyang** [comment]
We are almost ready. It should be very soon to release v6.0

**Comment by Pilchard123** [comment]
Awesome! I've been looking for something like this for months, and everything I've found has either been deprecated or requires server config changes that I'm pretty sure customers won't like. If this does what I'll need (and it certainly looks like it does), you'll have at least one very happy user.

**Comment by leecow** [comment]
The update to target net60 has been completed and announced in https://github.com/microsoft/IIS.Administration/issues/314.
