### ISSUE TITLE
Can't change port of IIS Administration Portal

### ISSUE THREAD

**Issue by Trickk** [Microsoft/IIS.Administration#308]
Hi,

For security reason I have to change the port of IIS Administration Portal.

I tried to edit "setup.config" but I have an error tht other process is using it.

I stoped the service and try again and still can't edit the file

SO: Windows Server 2019 Standard
IIS Administration Version: 2.2.1

**Comment by yaqiyang** [comment]
It is in appsettings.json. Add "urls" string as below,

 "host_id": "",
  "host_name": "IIS Administration API",
  **"urls": "https://*:55538",**
  "security": {
    "require_windows_authentication": true,
