### ISSUE TITLE
Change Port

### ISSUE THREAD

**Issue by yavuzcosar** [Microsoft/IIS.Administration#32]
Hi, i want to change localhost:55539 port to 8081 but not working
1. change setup.config;  <Port>55539</Port>
2. change applicationHost.config 
3. Restart Windows Service.

**Comment by jimmyca15** [comment]
What OS are you running and what method of installation did you use?

**Comment by yavuzcosar** [comment]
Azure VM - Windows Server 2012 R2 and i used http://manage.iis.net installation link

**Comment by jimmyca15** [comment]
Okay thank you for the info. If you have already updated the applicationHost.config file to point to the new port, then the only remaining work item is to register the SSL cert on the new port. The setup.config file is only used to document the installation and plays no role in the behavior of the application.

### Registering the certificate on a new port
To register the certificate on a new port the _netsh_ command line tool can be used. To bind a certificate to a port with netsh you need:
* The application id of the application using the port
* The certificate hash
* The ip + port combination to bind to.

1\. First we get the certificate hash by checking out the binding that was created during installation. 
```
c:\>netsh http show sslcert ipport="0.0.0.0:55539"

SSL Certificate bindings:
-------------------------

    IP:port                      : 0.0.0.0:55539
    Certificate Hash             : <Certificate hash will be here>
    Application ID               : {4dc3e181-e14b-4a21-b022-59fc669b0914}
    Certificate Store Name       : MY
    Verify Client Certificate Revocation : Enabled
    Verify Revocation Using Cached Client Certificate Only : Disabled
    Usage Check                  : Enabled
    Revocation Freshness Time    : 0
    URL Retrieval Timeout        : 0
    Ctl Identifier               : (null)
    Ctl Store Name               : (null)
    DS Mapper Usage              : Disabled
    Negotiate Client Certificate : Disabled
    Reject Connections           : Disabled
```

2\. Then we register the certificate on the new port
```
c:\>netsh http add sslcert ipport="0.0.0.0:8081" appid={4dc3e181-e14b-4a21-b022-59fc669b0914} certhash=<Certificate hash goes here>

SSL Certificate successfully added
```
