### ISSUE TITLE
0x80070643 Error WS2016 (IIS 10)

### ISSUE THREAD

**Issue by Ctancred** [Microsoft/IIS.Administration#323]
I've looked through all previous 0x80070643 error issues and nothing seems to relate.

Trying to install IIS Administrator 6.0 onto WS2016 Standard with IIS10. I have snipped and attached all versions of .NET installed on the server as well as the log files from installation. I have tried to repair all installations of .NET and attempted to install IIS Admin. This is a fresh install of IIS Admin, it hasn't been installed before.

Looking at the log file it seems to be ok will all the .NET versions. 

Any thoughts?

[Microsoft_IIS_Administration_6.0.0_20230928104522.log](https://github.com/microsoft/IIS.Administration/files/12748050/Microsoft_IIS_Administration_6.0.0_20230928104522.log)
![Capture](https://github.com/microsoft/IIS.Administration/assets/37186881/fa760e67-8b07-472f-9cdc-0da4707f1f03)

**Comment by firth** [comment]
Yeah, we're having the same exact problem on Windows Server 2022.

**Comment by yaqiyang** [comment]
Please provide this log, C:\Users\TANK\AppData\Local\Temp\Microsoft_IIS_Administration_6.0.0_20230928104522_001_iis_administration_msi.log
