### ISSUE TITLE
Log files and auditing are not migrated on upgrade.

### ISSUE THREAD

**Issue by jimmyca15** [Microsoft/IIS.Administration#33]
The log files that are created during usage of the application are not migrated on upgrade.
### Proposed Solution

Move the logs folder to be directly under the installation folder. Ex:
Move
`
C:\Program Files\IIS Administration\1.0.37\Microsoft.IIS.Administration\logs
`
to
`
C:\Program Files\IIS Administration\logs
`

**Comment by drago-draganov** [comment]
It's a default location only. It can still be customized via appsettings.json
