### ISSUE TITLE
Using own (custom UI)

### ISSUE THREAD

**Issue by rdzidziguri** [Microsoft/IIS.Administration#38]
Because of enterprise security policy we are not allowed to do setup in the way it is described on "Using the new API" section. navigating to manage.iis.net is not option for us so we decided to create sort of Octopus tentacle on which will be deployed on server in order to use it and create centralized dashboard for servers. is there any way how we can obtain tokens so that our internal application is able to go to machines and use API?
    Install administration API on server.
    install tentacle on server.
    Obtain access token from tentacle simple screen.

    Navigate to http://our-dashboard.local
    Click Add machine
    Enter the Access Key obtained from tentacle installation on server.
    Machine is added to the dashboard.

**Comment by shirhatti** [comment]
Access tokens can be generated via the API using the `/security/api-keys` route.
By default only members of the `Administrators` group and `IIS Administrators` group (that we create) can generate access tokens.

Additionally, if your Custom UI is browser-based, you'll need change your CORS policy to allow requests from you app. The CORS policy is defined in the `appsetttings.json` file. By  default we only grant access to https://manage.iis.net/ and you might want to change that.

**Comment by rdzidziguri** [comment]
@shirhatti Thank u very much for your answer. the idea here is no persons will be allowed to access API directly. what will happen is, local service (also developed on top of Net Core 1.0) will be installed which communicates to IIS Administration API and it sends back information to centralized dashboard. than we are aggregating information and show those as a single dashboard to environment and machine based cards.

**Comment by jimmyca15** [comment]
I believe the question here was answered. Please re-open if that is not the case.
