### ISSUE TITLE
Expose numerical site ID trough the API

### ISSUE THREAD

**Issue by ridercz** [Microsoft/IIS.Administration#39]
Currently there is no way how to get the numerical site ID used by the rest of IIS administration tools. I think the API should expose this information in addition to your internal string ID, because it's basically the only way how to reliably correlate sites across different administration tools/APIs.

**Comment by jimmyca15** [comment]
The site resource already has a field with the name _id_. We must use a name that does not cause confusion with the API id of the site.

Options discussed:
* config_id
* apphost_id
* config_key
* site_number
* config_number
* site_index

**Comment by jimmyca15** [comment]
Implemented in 7b378a2
