### ISSUE TITLE
Support for Web Hosting certificate store

### ISSUE THREAD

**Issue by ridercz** [Microsoft/IIS.Administration#40]
Currently, when working with certificates, the only exposed store is "My" (or "Personal"). This store is not intended and performant enough for web hosting, so WebHosting store was added in Windows 2012.

The store name is hardcoded in CertificateHelper class to be `public const StoreName STORE_NAME = StoreName.My;`. Please note: the `StoreName` enum does not contain value for WebHosting store, you have to open the store this way: `var store = new X509Store( "WebHosting", StoreLocation.LocalMachine);`.

**Comment by jimmyca15** [comment]
Support for the WebHosting certificate store has been added with the 1.1.0 release 52e07bd40355eb6a4de3d32ab8c19f35dcabe9ed.
