### ISSUE TITLE
Use OData instead of in-house syntax

### ISSUE THREAD

**Issue by ridercz** [Microsoft/IIS.Administration#44]
Use OData standard for queries, not your own syntax. There are MS libraries for both server and client side.

**Comment by drago-draganov** [comment]
Good point!
Using OData only for queries would bring the question for full OData application protocol support like metadata, data sets/entities, relations, invoking functions, etc. 
While OData is great for interaction with data and data heavy services, it's hard to say that every RESTful service should be OData based. IIS Administration API is more management and less data query intensive. It also doesn't require data interoperability between different systems. 
Our initial goal was to focus on simple, low level API first, minimalistic hypermedia support (via HAL in this case) and utilize Swagger for extensive document specification and proxy generation. 
Saying that, OData is not totally off the table for future releases. We are also keeping an eye on other emerging competitive protocols.

**Comment by ridercz** [comment]
I don't think it's necessary to bring full OData support, for reasons you stated. But I think you should use the URL syntax. Ie. instead of `fields` use `$select` etc. Why invent your own syntax, when there is something generally available?

**Comment by drago-draganov** [comment]
Using fields as query parameter to request partial response isn't in-house invention per se. It's been adopted by Facebook, Google and others.

Facebook Graph API
https://developers.facebook.com/docs/graph-api/using-graph-api

Google API
https://developers.google.com/+/web/api/rest/#partial-response

**Comment by jimmyca15** [comment]
Closing this discussion.
