### ISSUE TITLE
Document access token flow

### ISSUE THREAD

**Issue by trondhindenes** [Microsoft/IIS.Administration#45]
I'd like to use this with another config managment system. The UI is fine, but I can't find any documentation of how the token flow works or any swagger spec to help me. 

Could you please document in detail how to get an access token using a generic http client such as curl or PowerShell's invoke-restmethod/invoke-webrequest?

**Comment by jimmyca15** [comment]
Hello @trondhindenes ,

Here is a PowerShell example. https://github.com/Microsoft/IIS.Administration/blob/dev/scripts/utils.ps1#L35

Here is a C# example that we use in our tests. https://github.com/Microsoft/IIS.Administration/blob/dev/test/Microsoft.IIS.Administration.Tests/Utils.cs#L20

In both cases, to generate a token you must be an Administrator or IIS Administrator on the machine.

**Comment by trondhindenes** [comment]
Nice, thanks!

**Comment by jimmyca15** [comment]
No problem. We are working on documentation to provide more helpful examples. If anything is unclear in the provided examples let us know.
