### ISSUE TITLE
windows 7 Write-Error Could not get the state of IIS-HostableWebCore

### ISSUE THREAD

**Issue by cx-emerge** [Microsoft/IIS.Administration#57]
windows 7 Write-Error Could not get the state of IIS-HostableWebCore

```shell
D:\software\iis.administration\setup> .\setup.ps1 Install -Verbose -Port 55555
详细信息: Verifying user is an Administrator
详细信息: Ok
详细信息: Verifying user is an Administrator
详细信息: Ok
Checking installation requirements
详细信息: Verifying IIS is enabled
详细信息: Ok
详细信息: Verifying Windows Authentication is Enabled
详细信息: Ok
详细信息: Verifying URL Authorization is Enabled
详细信息: Ok
详细信息: Verifying IIS-HostableWebCore is Enabled
Rolling back
Finished rolling back.
Write-Error : Could not get the state of IIS-HostableWebCore
所在位置 D:\software\iis.administration\setup\dependencies.ps1:51 字符: 10
+     throw <<<<  "Could not get the state of $_featureName"
所在位置 D:\software\iis.administration\setup\setup.ps1:232 字符: 16
+     Write-Error <<<<  -Exception $_.exception -Message $($_.Exception.Message + [Environment]::NewLine + $_.Invocatio
nInfo.PositionMessage)
    + CategoryInfo          : NotSpecified: (:) [Write-Error], RuntimeException
    + FullyQualifiedErrorId : System.Management.Automation.RuntimeException,Microsoft.PowerShell.Commands.WriteErrorCo
   mmand
```

**Comment by jimmyca15** [comment]
Can you run the following command from PowerShell as an Administrator?

`
dism.exe /Online /Get-FeatureInfo /FeatureName:"IIS-HostableWebCore"
`

**Comment by cx-emerge** [comment]
```powershell
PS D:\software\iis.administration\setup> dism.exe /Online /Get-FeatureInfo /FeatureName:"IIS-HostableWebCore"

部署映像服务和管理工具
版本: 6.1.7600.16385

映像版本: 6.1.7601.18489

功能信息:

功能名称 : IIS-HostableWebCore
显示名称 : Internet Information Services 可承载的 Web 核心
描述 : 对应用程序进行编程，以利用核心 IIS 功能为 HTTP 请求提供服务。
需要重新启动 : Possible
状态 : 已启用

自定义属性:

(没有找到任何自定义属性)

操作成功完成。
```

```powershll
PS D:\software\iis.administration\setup> .\setup.ps1 Install -Verbose -Port 55555
详细信息: Verifying user is an Administrator
详细信息: Ok
详细信息: Verifying user is an Administrator
详细信息: Ok
Checking installation requirements
详细信息: Verifying IIS is enabled
详细信息: Ok
详细信息: Verifying Windows Authentication is Enabled
详细信息: Ok
详细信息: Verifying URL Authorization is Enabled
详细信息: Ok
详细信息: Verifying IIS-HostableWebCore is Enabled
Rolling back
Finished rolling back.
Write-Error : Could not get the state of IIS-HostableWebCore
所在位置 D:\software\iis.administration\setup\dependencies.ps1:51 字符: 10
+     throw <<<<  "Could not get the state of $_featureName"
所在位置 D:\software\iis.administration\setup\setup.ps1:232 字符: 16
+     Write-Error <<<<  -Exception $_.exception -Message $($_.Exception.Message + [Environment]::NewLine + $_.Invocatio
nInfo.PositionMessage)
    + CategoryInfo          : NotSpecified: (:) [Write-Error], RuntimeException
    + FullyQualifiedErrorId : System.Management.Automation.RuntimeException,Microsoft.PowerShell.Commands.WriteErrorCo
   mmand
```

**Comment by jimmyca15** [comment]
Thanks for your response. I see the issue. It is this line here https://github.com/Microsoft/IIS.Administration/blob/dev/scripts/setup/dependencies.ps1#L48. This check will have to be reworked to avoid breaking because of localization.

**Comment by jimmyca15** [comment]
There is a workaround for this. The checks for IIS, URL Auth, Hostable Web Core, and .NET 3.5 (only required on Win7 and 2008 R2) can be skipped by passing the -SkipVerification flag while installing.

When doing this workaround you have to manually ensure that all the Windows dependencies are enabled.

```
# Make sure IIS is enabled
Get-Service W3SVC

# Enable IIS components
dism.exe /Online /Enable-Feature /FeatureName:"IIS-WindowsAuthentication"
dism.exe /Online /Enable-Feature /FeatureName:"IIS-URLAuthorization"
dism.exe /Online /Enable-Feature /FeatureName:"IIS-HostableWebCore"
dism.exe /Online /Enable-Feature /FeatureName:"NetFx3"

# Then run the installation script skipping the step to check for these dependencies.
.\setup.ps1 Install -Verbose -Port 55555 -SkipVerification
```

**Comment by GISMaster** [comment]
@jimmyca15 Hi~ , I meet the same issue.  First I followed your job , the result is 
  
	详细信息: Verifying user is an Administrator
	详细信息: Ok
	详细信息: Verifying user is an Administrator
	详细信息: Ok+     Checking installation requirements
	详细信息: Verifying .NET Core shared framework installed
	详细信息: Ok
	详细信息: Verifying AspNet Core Module is installed
	详细信息: Ok
	详细信息: Ok
	详细信息: Checking if port '55555' is available
	详细信息: Ok
	详细信息: Verifying that IIS Administrators group does not already exist
	Installation Requirements met
	详细信息: Creating installaton directory C:\Program Files\IIS
	Administration\1.0.38
	Copying files
	详细信息: Creating new IIS Administration Certificate
	详细信息: Adding the certificate to trusted store
	详细信息: Binding Certificate to port 55555 in HTTP.Sys
	[SC] CreateService 成功
	Rolling back
	Rolling back service creation
	Rolling back HTTP.Sys port binding
	Rolling back setup config creation
	Rolling back SSL certificate creation
	警告: Could not delete certificate that was created during installation.
	Rolling back IIS Administrators group creation
	Rolling back installation folder creation
	Finished rolling back.
	Write-Error : Could not start service
	所在位置 O:\GitHub\IIS.Administration\output\setup\install.ps1:499 字符: 14
	throw <<<<  "Could not start service"
	所在位置 O:\GitHub\IIS.Administration\output\setup\setup.ps1:245 字符: 16
	+     Write-Error <<<<  -Exception $_.exception -Message $($_.Exception.Message
	 + [Environment]::NewLine + $_.InvocationInfo.PositionMessage)
	    + CategoryInfo          : NotSpecified: (:) [Write-Error], RuntimeExceptio
 	  n
	+ FullyQualifiedErrorId : System.Management.Automation.RuntimeException,Mi
	crosoft.PowerShell.Commands.WriteErrorCommand

    How to do next ？ need your help～ 3ks！

**Comment by jimmyca15** [comment]
@GISMaster Are you also using Windows 7?

Can you verify that all the dependencies were enabled successfully?

```
dism.exe /Online /Get-FeatureInfo /FeatureName:"IIS-WindowsAuthentication"
dism.exe /Online /Get-FeatureInfo /FeatureName:"IIS-URLAuthorization"
dism.exe /Online /Get-FeatureInfo /FeatureName:"IIS-HostableWebCore"
dism.exe /Online /Get-FeatureInfo /FeatureName:"NetFx3"
```

**Comment by GISMaster** [comment]
@jimmyca15 Yes, now I using Windows 7 ,these component can't be used in this System?
All the dependencies were enabled succesfully ! But when I used this script , the issue come here~
	.\setup.ps1 Install -Verbose -Port 55555 -SkipVerification

**Comment by jimmyca15** [comment]
@GISMaster We support Windows 7. Thanks for making sure everything was enabled. The problem is coming from starting the service so there are multiple things that can be at play here.

Can you confirm that dotnet core was installed correctly on your machine?

The default installation path for dotnet is 
`
C:\Program Files\dotnet\shared\Microsoft.NETCore.App
`
Make sure that you see a folder with the name _1.0.{some number}_

Then make sure the following command can execute
`
dotnet.exe
`

If dotnet core is installed correctly the service might not be able to start because the operating system is not up to date. Windows 7 requires[ KB2999226](https://support.microsoft.com/en-us/help/2999226/update-for-universal-c-runtime-in-windows) to be able to run the service.

**Comment by GISMaster** [comment]
@jimmyca15 Thanks for your help ! The service could be running now , when I installed KB2999226 on my Windows 7 System.

**Comment by jimmyca15** [comment]
@GISMaster,
Great, thanks for using the service. If there are any more problems please open another issue.
