### ISSUE TITLE
Error starting service "Microsoft IIS Administration"

### ISSUE THREAD

**Issue by Loucool111** [Microsoft/IIS.Administration#59]
Hello,

I'm trying to install the administration tools on a Nano server and I'm getting this error message : 

![error](https://cloud.githubusercontent.com/assets/8092199/22069358/76840c86-dd98-11e6-8efe-de2b5eeaabf7.PNG)

The error occurs when the install script tries to start the newly created "Microsoft IIS Administration" service. Any advice ?

Thanks in advance !

**Comment by jimmyca15** [comment]
Hello @Loucool111,

Can you verify that the required IIS Features were enabled by running the following script?
```
Get-Service w3svc
Get-WindowsOptionalFeature -Online -FeatureName "IIS-WindowsAuthentication"
Get-WindowsOptionalFeature -Online -FeatureName "IIS-URLAuthorization"
```

The service should exist and the features should be in the _Enabled_ state.

_dotnet.exe_ should be on your **system path** so that the service can access it.

```
# Assuming dotnet was placed at C:\Program Files\dotnet, the following lines will add dotnet.exe to the system path variable
# $env:Path | Out-File "C:\PathBeforeDotNet.txt"
# setx PATH "$($env:Path);C:\Program Files\dotnet" /m
```

Another pitfall may be that the machine does not have the VC2015 runtime
```
Write-Host "Visual Studio 2015 C++ Redistributable already installed?"
Write-Host "$(Test-Path C:\Windows\System32\vcruntime140.dll)"
```

**Comment by Loucool111** [comment]
Hello,

Thanks for the quick answer !

I've checked everything you subjected and here are the results : 

![e1](https://cloud.githubusercontent.com/assets/8092199/22096635/feacf648-de1c-11e6-8fce-43d8eb6ad2d2.PNG)

w3svc service is running and "IIS-WindowsAuthentication" is enabled,

![e2](https://cloud.githubusercontent.com/assets/8092199/22096656/1433df90-de1d-11e6-9eb4-87c2ae50910a.PNG)

"IIS-URLAuthorization" is also installed.

my "dotnet.exe" is installed at "C:\Users\Administrator\AppData\Local\Microsoft\dotnet"
and the system path is configured : 

![e3](https://cloud.githubusercontent.com/assets/8092199/22096717/5decd56a-de1d-11e6-961f-c61d0b43a66f.PNG)

Finally, the vcruntime140.dll is there.

I've tried to re-run the setup script like I did in the first place and I still get the same error.

Is there anything else I need to check ?

Thanks in advance !

**Comment by jimmyca15** [comment]
Ok, I see that all the required features are enabled. Dotnet.exe may have been added to your user path rather than the **system** path. This would prevent the service from being able to access dotnet.exe. To investigate this, list the system path using

```
(Get-Itemproperty 'HKLM:\SYSTEM\CurrentControlSet\Control\Session Manager\Environment').path
```

Confirm that there is an entry for _C:\Users\Administrator\AppData\Local\Microsoft\dotnet_

**Comment by Loucool111** [comment]
I can confirm that the the path is correct in the registry :

![e5](https://cloud.githubusercontent.com/assets/8092199/22118977/065eef06-de7a-11e6-8038-f84626e602fd.PNG)

**Comment by Loucool111** [comment]
Opps wrong button, anyway here are my results :

![e5](https://cloud.githubusercontent.com/assets/8092199/22119013/2d5d0be2-de7a-11e6-8409-4bad7f835a32.PNG)

**Comment by jimmyca15** [comment]
Sorry I was so delayed in my response. I just booted up a fresh Nano Server machine and went through the installation process to see if I could reproduce the issue. I was not able to reproduce the issue, however I did need to _restart the machine_ in order for the service to install and run correctly. This may have nothing to do with your issue.

Can you try running 

```
cd c:\iis.administration\microsoft.iis.administration\
dotnet microsoft.iis.administration.dll
```

Knowing the result effectively cuts the amount of possible issues in half.

![image](https://cloud.githubusercontent.com/assets/21000428/22133702/cae46170-de76-11e6-8c90-fa7048bcc305.png)

If it starts up make sure to exit with _ctrl+c_

**Comment by Loucool111** [comment]
Hello, 

Sorry for the late response, here's what I got :

![e6](https://cloud.githubusercontent.com/assets/8092199/22193865/d4ee1466-e13e-11e6-99a3-c212ebf454c3.PNG)

Executing it like this seems to work !

What's left to test ?

**Comment by jimmyca15** [comment]
The application is running as expected when invoked directly. The only difference between executing it that way and via the service is the involvement of IIS. So there has to be something wrong with the _IIS setup_ on the machine.

Can you confirm that you have the ASP.Net Core Module placed on the machine?

```
Write-Host "ASP.Net Core Module already installed?"
Write-Host "$(Test-Path C:\Windows\System32\inetsrv\aspnetcore.dll)"
```

I just removed my aspnetcore.dll from my nano machine and I got the same error that you are getting.

**Comment by Loucool111** [comment]
I can confirm that the ASP.Net Core Module is prensent :

![e7](https://cloud.githubusercontent.com/assets/8092199/22246277/543c4288-e234-11e6-8428-299383b00028.PNG)

I copied it from my base machine (W10 Enterprise) in C:\Program Files\IIS Express

**Comment by jimmyca15** [comment]
Hello Loucool111,

I see that the ASP.Net Core Module was not the cause of the issue. Are you still experiencing this?

**Comment by Loucool111** [comment]
Hello,

Yes, I am still running into this issue.

**Comment by jimmyca15** [comment]
Okay there is another issue at play with the IIS configuration on the machine that is causing the service not to start up.

The following PowerShell command will help me better understand the configuration that you're using for IIS.

```
```

**Comment by mbp** [comment]
I have the same problem as original poster. Here are my enabled features (I tried to enable HttpCompressionStatic feature without luck):

    FeatureName : IIS-WebServerRole
    State       : Enabled

    FeatureName : IIS-WebServer
    State       : Enabled

    FeatureName : IIS-CommonHttpFeatures
    State       : Enabled

    FeatureName : IIS-StaticContent
    State       : Enabled

    FeatureName : IIS-DefaultDocument
    State       : Enabled

    FeatureName : IIS-DirectoryBrowsing
    State       : Enabled

    FeatureName : IIS-HttpErrors
    State       : Enabled

    FeatureName : IIS-HttpRedirect
    State       : Disabled

    FeatureName : IIS-ApplicationDevelopment
    State       : Disabled

    FeatureName : IIS-CGI
    State       : Disabled

    FeatureName : IIS-ISAPIExtensions
    State       : Disabled

    FeatureName : IIS-ISAPIFilter
    State       : Disabled

    FeatureName : IIS-ServerSideIncludes
    State       : Disabled

    FeatureName : IIS-WebSockets
    State       : Disabled

    FeatureName : IIS-ApplicationInit
    State       : Disabled

    FeatureName : IIS-Security
    State       : Enabled

    FeatureName : IIS-BasicAuthentication
    State       : Disabled

    FeatureName : IIS-WindowsAuthentication
    State       : Enabled

    FeatureName : IIS-DigestAuthentication
    State       : Disabled

    FeatureName : IIS-ClientCertificateMappingAuthentication
    State       : Disabled

    FeatureName : IIS-IISCertificateMappingAuthentication
    State       : Disabled

    FeatureName : IIS-URLAuthorization
    State       : Enabled

    FeatureName : IIS-RequestFiltering
    State       : Enabled

    FeatureName : IIS-IPSecurity
    State       : Disabled

    FeatureName : IIS-CertProvider
    State       : Disabled

    FeatureName : IIS-Performance
    State       : Enabled

    FeatureName : IIS-HttpCompressionStatic
    State       : Enabled

    FeatureName : IIS-HttpCompressionDynamic
    State       : Disabled

    FeatureName : IIS-HealthAndDiagnostics
    State       : Enabled

    FeatureName : IIS-HttpLogging
    State       : Enabled

    FeatureName : IIS-LoggingLibraries
    State       : Disabled

    FeatureName : IIS-RequestMonitor
    State       : Disabled

    FeatureName : IIS-HttpTracing
    State       : Disabled

    FeatureName : IIS-CustomLogging
    State       : Disabled

**Comment by jimmyca15** [comment]
It shows that the HTTP Compression feature is enabled in the output you posted. Do you mean there was some issue when you enabled it?

**Comment by mbp** [comment]
Yes, the service worked directly.

The aspnetcore module is installed

**Comment by jimmyca15** [comment]
@mbp,

Thanks for the information. It seems unlikely that one of the disabled features are the cause of the service not starting but that is where i will begin my investigation as to the cause of this issue on Nano Server.

**Comment by jimmyca15** [comment]
@mbp,

Did you install the vc 2015 runtime on the Nano Server machine?

```
Write-Host "$(Test-Path C:\Windows\System32\vcruntime140.dll)"
```

**Comment by mbp** [comment]
I don't have access to this machine any longer, but I was following this guide, which tells you to install vc 2015 runtime: https://blogs.iis.net/adminapi/microsoft-iis-administration-on-nano-server

So can't verify that command sorry.

**Comment by jimmyca15** [comment]
@mbp,

Okay thanks for filing the issue. The only repro we found was not having the VC Runtime (vcruntime140.dll) available. We have added an explicit requirement for it in the new setup script #71.

**Comment by kae** [comment]
https://github.com/Microsoft/IIS.Administration/blob/dev/src/Microsoft.IIS.Administration/ConfigurationHelper.cs#L21
```c#

            RootPath = Environment.GetEnvironmentVariable("ASPNETCORE_ENVIRONMENT") != null ?
                       Directory.GetCurrentDirectory() : Path.GetDirectoryName(System.Reflection.Assembly.GetEntryAssembly().Location);
```

This code gets different paths for system with ASPNETCORE_ENVIRONMENT set and without it

So on development servers it's going to get default service directory and throw exception of not finding config directory.

Is there any sensible reason for not just using `Path.GetDirectoryName(System.Reflection.Assembly.GetEntryAssembly().Location)` on all systems?

**Comment by jimmyca15** [comment]
@drago-draganov 

The code was added because the application structure has some differences between when we develop and when we run it in production (non-development). 

@kae Are you setting the ASPNETCORE_ENVIRONMENT variable system wide on your development servers and if so what value are you using?
