### ISSUE TITLE
Shared Configuration API

### ISSUE THREAD

**Issue by jimmyca15** [microsoft/IIS.Administration#66]
The API should support [Shared Configuration](https://www.iis.net/learn/manage/managing-your-configuration-settings/shared-configuration_264#02)
* Enabling shared configuration
* Export/import necessary files for shared configuration

**Comment by affieuk** [comment]
Is there any road map or timeline for this feature? As a work around I've configured Shared Configuration and then browsing api/webserver I can see the test sites I've added. Do you see any issues with this?

**Comment by jimmyca15** [comment]
@affieuk We do not currently have a date for when this feature will be added to the API. What I can say is that it is high on our priority for future releases.

If you have shared configuration enabled, it can be manipulated through the API successfully so I would expect the sites to show up as you have described. The Shared Configuration API mentioned in this issue would be to enable/disable shared configuration.

**Comment by affieuk** [comment]
Also I'm not sure if this is completely related, however is it possible to install IIS Administration but point it to a remote server, i.e. give it a UNC path to the IIS .config files?

**Comment by jimmyca15** [comment]
@affieuk 

There is currently know way to modify the location of the applicationHost.config that the API is set to configure. It will look for this file in `%systemdrive%\windows\system32\inetsrv\config`. However, web.config files located on network shares will be configurable of course if the sites are located there.
