### ISSUE TITLE
Add ability to install/uninstall IIS optional features

### ISSUE THREAD

**Issue by jimmyca15** [Microsoft/IIS.Administration#72]
In 1.0.39 and below the API returns 404 for endpoints that use an IIS feature that is not installed. There is no way to install the feature through the API to start using the endpoint. The API should provide the capability to install all of the IIS optional features that come with the OS. A new installation of the API should be capability of enabling all of the IIS functionality the API exposes for management.

## Proposal
Features that are uninstalled will continue to return a 404 with a **FeatureNotInstalled** error object. 

### Install
Sending a **POST** request to the feature's endpoint without the _{id}_ parameter will create the resource on the server by installing the feature.

### Uninstall
Uninstall will be handled by sending a **DELETE** request to the feature's endpoint without the _{id}_ parameter.

**Comment by drago-draganov** [comment]
DELETE better accept {id}. All optional IIS features are represented as ID-ed object.
POST returns HTTP 201 Created, with Location pointing to the server level resource. DELETE shall work on that url.

**Comment by jimmyca15** [comment]
This functionality has been added in the 1.1.0 release
