### ISSUE TITLE
ARR (Application Request Routing) Support

### ISSUE THREAD

**Issue by StephenShamakian** [microsoft/IIS.Administration#79]
Does the IIS RestAPI support the ARR (Application Request Routing) module?

**Comment by jimmyca15** [comment]
There is no API for ARR yet. This is on our road map along with support for shared configuration and url rewrite.

**Comment by radderz** [comment]
Hi, you mention a roadmap, can you make this public? We are really interested in this feature for simplifying publishing and load balancing.

**Comment by jamesharling** [comment]
@jimmyca15 Is there an ETA for ARR support? APIs for this will open many doors for us, and many others out there I'm sure!

**Comment by tbonham** [comment]
Please add it as I'm working on deploying it now.

**Comment by MajMcCloud** [comment]
Hey gentlemen,

I'm bringing this topic back up.
Is there any work going on ?
There are some small things which could really bring a lot of improvements to the UI and stuff.

Any idea to make this plugin open source ? So multiple developers can contribute or extend on their own?

Thank you!

Warm regards
Florian Dahn
