### ISSUE TITLE
Compile against new .Net Core 1.1.1

### ISSUE THREAD

**Issue by johnwc** [Microsoft/IIS.Administration#89]
What's the likelihood of getting a release updated to work with .Net Core 1.1.1? I wasted a lot of time trying to get 1.0 installed on a Nano server with the dotnet-install.ps1 script. None of the channels seem to be there anymore for 1.0.

**Comment by jimmyca15** [comment]
Hello @johnwc,

We currently are not planning to target .NET Core 1.1.*. The install script for .NET Core on Nano Server should contain both the LTS (1.1.*) and FTS (1.0.*) branch of .NET Core. May I ask where you obtained the dotnet-install.ps1 script?

**Comment by jimmyca15** [comment]
Hey @johnwc,

I'd like to add to my previous comment.

.NET Core has 2 version trains: Long Term Support (1.0.\*) and Fast Track Support (1.\*.\*). .NET Core 1.1.1 is on the FTS branch of .NET Core. Choosing to use the FTS branch means access to newer features/APIs but requires developers to move at a quicker cadence to stay within support. Taking this dependency also means users of the software will have to continuously download and install the newest version of .NET Core to run the applications. Using the LTS branch means developers will have access to the APIs that were available with initial release, but will continue to receive support for a lengthy period. This approach should also result in less overhead for system administrators to be able to run the applications.

The FTS branch (1.1.1) __does not__ replace the LTS branch (1.0.4). They are side-by-side and both should be easily obtainable.

I hope that is a good enough explanation of our reasoning, if you have any more questions please reopen this or another issue.

I also would like to mark the issue tracking the installation problem that prompted this as a reference
https://github.com/dotnet/cli/issues/6549
