### ISSUE TITLE
Credentials and Token

### ISSUE THREAD

**Issue by AlenPelin** [Microsoft/IIS.Administration#92]
The first code sample in readme outlines that credentials are required as much as a token, but is this really necessary? I mean, it is clear that credentials are required to get a token, but it should be enough to have a token without credentials for all other operations, shouldn't it? However it seems that the token is not sufficient with current 1.1.1 version of service as the response is always 403.

**Comment by pillartec** [comment]
I have the same issue when trying to connect to any servers I should input credentials and token for each of them.  It's not usability as for me.

**Comment by AlenPelin** [comment]
@pillartec well, in theory it should be possible to turn off windows authentication via configuration file, but at the same time need to ensure that it is still required to authorize to get a token.

**Comment by jimmyca15** [comment]
Security has been our number one priority as we have developed the IIS Administration API. This tool will be used to manage web servers so it is essential that we provide a multitude of methods for users to restrict access. Many users will have different requirements based on their environment, and we deliver the API with the configuration that we feel is the most secure and most usable for most. It is possible to remove the Windows Authentication requirements and rely solely on the access token as mentioned here https://github.com/Microsoft/IIS.Administration/issues/86#issuecomment-302260245.

**Comment by AlenPelin** [comment]
Thanks @jimmyca15 for explanation. What is the purpose of having tokens enabled by default then? Having creds we can always generate token - even new token for every new operation. So what's the purpose? Does it make sense for you to change logic so that there is a switch when installing service:
* Windows authentication always, no access tokens required
* Access tokens to work with the service, Windows authentication to get tokens

**Comment by jimmyca15** [comment]
Windows Authentication alone is vulnerable to an attack called [Cross-Site Request Forgery (CSRF)](https://docs.microsoft.com/en-us/aspnet/web-api/overview/security/preventing-cross-site-request-forgery-csrf-attacks). It is standard for REST APIs to require some header token to protect from attacks such as this. Using the access token alone is acceptable because as you said, in order to generate an access token Windows Authentication must have been used in the first place.

**Comment by AlenPelin** [comment]
Thanks for clarification.
