### ISSUE TITLE
SSL certificate

### ISSUE THREAD

**Issue by PIXPOINT** [Microsoft/IIS.Administration#93]
If I want to add an SSL certificate to a page, I always get an error Messing:

_An invalid value was given for Certificate. 
Certificate does not support server authentication_

**Comment by jimmyca15** [comment]
In order to use SSL certificates with IIS, the SSL certificate must have been created for server authentication. The certificate resource has a field named _intended_purposes_. A valid certificate for use for SSL would have the _Server Authentication_ intended purpose.

Example:

```
        {
            "alias": "",
            "id": "{some_id}",
            "issued_by": "CN=localhost",
            "subject": "CN=localhost",
            "thumbprint": "{some_thumbprint}",
            "signature_algorithm": "sha256RSA",
            "valid_from": "2016-03-29T23:15:44Z",
            "valid_to": "2017-03-29T23:35:44Z",
            "version": "3",
            "intended_purposes": [
                "Server Authentication"
            ],
            "private_key": {
                "exportable": "false"
            },
            "subject_alternative_names": [
            ]
        }
```
